import Link from 'next/link'
import type { Metadata } from 'next'
import { buildBlogBreadcrumbLd, buildArticleLd, buildFaqLd } from '@/lib/schema'
import { BOOKING_LINK } from '@/lib/constants'
import FaqSection from '../_components/FaqSection'

export const metadata: Metadata = {
  title: 'E-Invoicing Under GST: Applicability Threshold & Process',
  description: 'Who must generate e-invoices under GST, the Rs 5 crore turnover threshold, the IRN/QR code process, the 30-day reporting rule for larger taxpayers, and penalties for non-compliance.',
  keywords: [
    'e-invoicing under GST', 'e-invoice applicability threshold', 'e-invoice Rs 5 crore limit',
    'e-invoice IRN QR code', 'e-invoicing process GST', 'who needs e-invoice GST',
    'e-invoice 30 day reporting rule', 'e-invoice penalty',
  ],
  alternates: { canonical: 'https://agrawalkhandelwal.com/blog/e-invoicing-gst-applicability-threshold' },
  openGraph: {
    title: 'E-Invoicing Under GST: Applicability Threshold & Process',
    description: 'The Rs 5 crore turnover threshold, IRN/QR code process, 30-day reporting rule, and penalties for e-invoicing non-compliance.',
    url: 'https://agrawalkhandelwal.com/blog/e-invoicing-gst-applicability-threshold',
    type: 'article',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'E-Invoicing Under GST: Applicability Threshold & Process',
    description: 'The Rs 5 crore turnover threshold, IRN/QR code process, and 30-day reporting rule for e-invoicing under GST.',
  },
}

const breadcrumbLd = buildBlogBreadcrumbLd('E-Invoicing Under GST: Applicability Threshold & Process', 'e-invoicing-gst-applicability-threshold')

const articleLd = buildArticleLd({
  headline: 'E-Invoicing Under GST: Applicability Threshold & Process',
  description: 'Who must generate e-invoices under GST, the Rs 5 crore turnover threshold, the IRN/QR code process, the 30-day reporting rule for larger taxpayers, and penalties for non-compliance.',
  datePublished: '2026-09-19',
  slug: 'e-invoicing-gst-applicability-threshold',
})

const faqs: [string, string][] = [
  [
    'What is the turnover limit for mandatory e-invoicing under GST?',
    'E-invoicing is mandatory for GST-registered businesses whose aggregate turnover has crossed Rs 5 crore in any financial year since 2017-18. The obligation is triggered by the highest turnover ever recorded from that year onward, not just the current year\'s figure, so a business that once crossed Rs 5 crore stays covered even if turnover later dips below that level.',
  ],
  [
    'Does e-invoicing apply to B2C invoices?',
    'No. The e-invoicing mandate applies to B2B supplies, exports, and deemed exports, where the recipient is a registered person or the transaction is a supply to SEZ or an export. B2C (business-to-consumer) invoices are outside the e-invoicing framework, though businesses covered by the mandate must still comply with the Dynamic QR Code requirement on B2C invoices where applicable.',
  ],
  [
    'What is the IRN and how is it generated?',
    'The Invoice Reference Number (IRN) is a unique hash generated by the government\'s Invoice Registration Portal (IRP) for each e-invoice submitted to it. The supplier uploads the invoice details (via their accounting/ERP software or the IRP\'s own tools) in the prescribed schema, the IRP validates and de-duplicates it, then returns a signed invoice with the IRN and a QR code. Only an invoice bearing a valid IRN is treated as a valid tax invoice for GST purposes once e-invoicing applies to that business.',
  ],
  [
    'What is the 30-day e-invoice reporting rule?',
    'Businesses with an aggregate annual turnover of Rs 10 crore or more must report each e-invoice to the IRP within 30 days of the invoice date; invoices reported after that window are rejected by the portal. This rule pushes larger taxpayers toward reporting invoices close to real time rather than batching them at month-end, so building e-invoice generation into daily billing workflows matters more as turnover grows.',
  ],
  [
    'What happens if a business fails to generate an e-invoice when required?',
    'An invoice issued without a valid IRN, where e-invoicing applies, is not treated as a valid tax invoice under GST. This can lead to denial of input tax credit to the recipient, a penalty on the supplier, and complications in claiming the transaction as a valid supply during a GST audit or assessment. Because the defect sits with the invoice itself, it is far cheaper to fix the billing process upfront than to untangle disputed invoices later.',
  ],
  [
    'Can a business voluntarily opt in to e-invoicing before crossing the threshold?',
    'Yes, the GST Council has allowed voluntary e-invoicing for taxpayers below the mandatory turnover threshold in certain notified categories. Businesses expecting to cross the threshold soon, or those dealing heavily with large corporate buyers who prefer IRN-backed invoices for their own input tax credit reconciliation, sometimes opt in early to build the process before it becomes compulsory.',
  ],
]

const faqLd = buildFaqLd(faqs)

const bookingLink = BOOKING_LINK

export default function EInvoicingApplicabilityBlog() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLd) }} />
      <div style={{ background: 'var(--bg-surface)', minHeight: '100dvh', paddingTop: '100px' }}>
        <div className="section">
          <div className="container">
            <Link href="/blog" style={{ color: 'var(--accent)', marginBottom: '2rem', display: 'inline-flex', alignItems: 'center', gap: '6px', fontWeight: 700 }}>
              &larr; Back to Insights
            </Link>
            <article className="card" style={{ maxWidth: '800px', margin: '0 auto' }}>
              <span className="section-badge">GST</span>
              <h1 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', marginTop: '1rem', marginBottom: '1rem', lineHeight: 1.25 }}>
                E-Invoicing Under GST: Applicability Threshold & Process
              </h1>
              <div style={{ display: 'flex', gap: '1rem', color: 'var(--text-light)', marginBottom: '2.5rem', fontSize: '0.9rem', fontWeight: 600, flexWrap: 'wrap', alignItems: 'center' }}>
                <span>Published September 19, 2026</span>
                <span aria-hidden>&bull;</span>
                <span>CA Mehul Agrawal</span>
                <span aria-hidden>&bull;</span>
                <span>Agrawal Khandelwal &amp; Associates LLP</span>
              </div>

              <div className="blog-content" style={{ fontSize: '1.05rem', lineHeight: '1.85', color: 'var(--text-main)' }}>
                <div style={{ padding: '1.5rem 1.75rem', background: 'var(--bg-main)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)', borderLeft: '4px solid var(--accent)', marginBottom: '2rem' }}>
                  <p style={{ fontWeight: 800, color: 'var(--accent)', marginBottom: '0.6rem', fontSize: '0.85rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}>TL;DR</p>
                  <ul style={{ margin: 0, paddingLeft: '1.25rem' }}>
                    <li style={{ marginBottom: '0.4rem' }}>E-invoicing is mandatory once aggregate turnover crosses <strong>Rs 5 crore</strong> in any financial year since 2017-18, and the obligation continues even if turnover later falls below that level.</li>
                    <li style={{ marginBottom: '0.4rem' }}>It applies to B2B, export, and deemed-export invoices; B2C invoices are outside the mandate.</li>
                    <li style={{ marginBottom: '0.4rem' }}>Taxpayers with turnover of <strong>Rs 10 crore or more</strong> must report each invoice to the government portal within <strong>30 days</strong>, or the portal rejects it.</li>
                    <li style={{ marginBottom: 0 }}>An invoice without a valid IRN, where the mandate applies, is not a valid tax invoice; this can cost the recipient their input tax credit.</li>
                  </ul>
                </div>

                <p>A surprising number of businesses that comfortably cross Rs 5 crore in turnover still generate invoices the old way, from accounting software or Excel, without realizing e-invoicing has become mandatory for them. The gap usually surfaces at the worst possible time, when a customer&apos;s finance team rejects an invoice for input tax credit because it lacks a valid IRN. Here is what actually triggers the requirement and how the process works.</p>

                <h2>Who Must Generate E-Invoices?</h2>
                <p>E-invoicing under GST is mandatory for registered businesses whose <strong>aggregate turnover has crossed Rs 5 crore</strong> in any financial year from 2017-18 onward. This is a cumulative, one-way trigger: once a business crosses Rs 5 crore in even one year, it remains covered by the mandate in all future years, regardless of whether turnover later drops below that figure. The threshold has been at Rs 5 crore since August 2023, having been progressively lowered from a much higher starting point when e-invoicing was first introduced.</p>
                <p>The mandate covers <strong>B2B supplies, exports, and deemed exports</strong> (including supplies to SEZ units). It does not apply to B2C invoices, though businesses within the e-invoicing mandate separately need to comply with Dynamic QR Code requirements on B2C invoices above a specified value, which is a distinct requirement from IRN generation.</p>

                <h2>How the E-Invoicing Process Works</h2>
                <ol>
                  <li><strong>Generate the invoice</strong> in your accounting or billing software in the standard e-invoice schema (JSON format).</li>
                  <li><strong>Upload it to the Invoice Registration Portal (IRP)</strong>, either directly, through GST-suvidha-provider integrations, or via API from your ERP/accounting software.</li>
                  <li><strong>The IRP validates the invoice</strong>, checks for duplication, and generates a unique <strong>Invoice Reference Number (IRN)</strong> along with a digitally signed QR code.</li>
                  <li><strong>The signed invoice with IRN and QR code is returned</strong> to the supplier, who then shares this final version with the buyer. This IRN-bearing invoice is what counts as a valid tax invoice for GST purposes.</li>
                  <li><strong>Invoice data flows automatically</strong> to the GST return system (GSTR-1) and, where applicable, to the e-way bill system, reducing duplicate data entry.</li>
                </ol>

                <h2>The 30-Day Reporting Window for Larger Taxpayers</h2>
                <p>Taxpayers with an aggregate annual turnover of <strong>Rs 10 crore or more</strong> face an additional constraint: each invoice must be reported to the IRP within <strong>30 days</strong> of the invoice date. Invoices submitted after this window are rejected outright by the portal, with no manual override. This rule pushes larger businesses to generate and report e-invoices close to the transaction date rather than batching them at month-end or quarter-end, which is a workflow change that needs to be built into the billing process, not handled as an afterthought during return filing.</p>

                <h2>Why an Invoice Without an IRN Is a Real Problem</h2>
                <p>Where e-invoicing applies, an invoice that does not carry a valid IRN is not treated as a valid tax invoice under GST law. The practical consequences fall on both sides of the transaction:</p>
                <ul>
                  <li><strong>For the buyer:</strong> Input tax credit claimed against a non-compliant invoice can be denied or challenged during assessment.</li>
                  <li><strong>For the supplier:</strong> Non-generation of a required e-invoice attracts penalty exposure, and the supply may not be recognised correctly in GSTR-1, creating a mismatch that surfaces during reconciliation or audit.</li>
                </ul>
                <p>Because large corporate buyers increasingly reconcile input tax credit against the government&apos;s e-invoice data automatically, a missing IRN is often caught by the customer&apos;s accounts payable team before it is caught internally, which makes it a relationship problem as much as a compliance one.</p>

                <h2>Voluntary E-Invoicing Below the Threshold</h2>
                <p>Businesses below Rs 5 crore turnover are not required to generate e-invoices, but voluntary enrolment has been permitted for certain notified taxpayer categories. Businesses growing quickly toward the threshold, or those transacting heavily with large enterprise customers who prefer IRN-backed invoices for their own reconciliation, sometimes build the e-invoicing workflow into their systems ahead of the mandatory cutover, so the transition does not disrupt billing when the threshold is eventually crossed.</p>
              </div>

              <div style={{ marginTop: '3.5rem', padding: '2.5rem', background: 'var(--bg-main)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }}>
                <h3 style={{ marginBottom: '0.75rem' }}>Not sure if e-invoicing applies to your business yet?</h3>
                <p style={{ color: 'var(--text-light)', marginBottom: '1.5rem', fontSize: '0.95rem' }}>We help businesses assess e-invoicing applicability, set up IRP integration, and stay compliant on GST returns and e-way bills.</p>
                <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap' }}>
                  <a href={bookingLink} target="_blank" rel="noopener noreferrer" className="btn btn-primary">Book Free Consultation</a>
                  <Link href="/services" className="btn btn-outline">View Our Services</Link>
                </div>
              </div>

              <FaqSection faqs={faqs} />

              <div style={{ marginTop: '3rem', padding: '1.5rem', background: 'var(--bg-main)', borderRadius: 'var(--radius-md)', border: '1px solid var(--border)' }}>
                <h3 style={{ fontSize: '1rem', marginBottom: '1rem' }}>Related Guides</h3>
                <ul style={{ margin: 0, paddingLeft: '1.25rem' }}>
                  <li style={{ marginBottom: '0.5rem' }}><Link href="/blog/e-way-bill-rules-validity-penalties" style={{ color: 'var(--primary)', fontWeight: 600 }}>E-Way Bill Rules: When Required, Validity & Penalties</Link></li>
                  <li style={{ marginBottom: '0.5rem' }}><Link href="/blog/gst-registration-startups-first-return" style={{ color: 'var(--primary)', fontWeight: 600 }}>GST Registration for Startups: When Required & First Return Guide</Link></li>
                  <li style={{ marginBottom: '0.5rem' }}><Link href="/blog/gst-on-exports-zero-rated-vs-exempt-india" style={{ color: 'var(--primary)', fontWeight: 600 }}>GST on Exports: Zero-Rated vs Exempt</Link></li>
                  <li style={{ marginBottom: 0 }}><Link href="/blog/startup-compliance-automation-odi-apr-gst" style={{ color: 'var(--primary)', fontWeight: 600 }}>Startup Compliance Automation: RBI ODI, APR, Transfer Pricing & GST</Link></li>
                </ul>
              </div>
            </article>
          </div>
        </div>
      </div>
    </>
  )
}
