import type { Metadata } from 'next'
import BlogGrid from './BlogGrid'

export const metadata: Metadata = {
  title: 'Tax & Business Insights Blog',
  description: 'CA insights on International Tax, Transfer Pricing, DTAA, UAE Corporate Tax, startup compliance, and NRI taxation. Agrawal Khandelwal & Associates LLP.',
  keywords: [
    'international tax insights India', 'transfer pricing India blog',
    'UAE corporate tax news', 'startup compliance India',
    'DTAA India guide', 'NRI taxation India',
    'GST compliance updates', 'CA insights India',
  ],
  alternates: { canonical: 'https://agrawalkhandelwal.com/blog' },
  openGraph: {
    title: 'Tax & Business Insights Blog',
    description: 'Expert insights on International Tax, Transfer Pricing, DTAA, UAE Corporate Tax, and startup compliance from our CA team.',
    url: 'https://agrawalkhandelwal.com/blog',
  },
}

const posts = [
  {
    title: 'TCS on Sale of Goods: What Happened to Section 206C(1H)',
    slug: 'tcs-sale-of-goods-section-206c1h-repealed',
    date: 'August 8, 2026',
    category: 'Income Tax',
    summary: 'Section 206C(1H), the seller-side TCS on sale of goods above Rs 50 lakh, was omitted from April 1, 2025 to remove duplication with buyer-side Section 194Q, and what applies now.',
  },
  {
    title: 'Standard Deduction for Salaried Employees: Current Limits',
    slug: 'standard-deduction-salaried-employees-limits',
    date: 'August 9, 2026',
    category: 'Income Tax',
    summary: 'The standard deduction is Rs 75,000 under the new regime and Rs 50,000 under the old regime for FY 2026-27, who gets it automatically, and how it factors into the regime choice.',
  },
  {
    title: 'Tax Saving Investment Options Beyond Section 80C',
    slug: 'tax-saving-investments-beyond-section-80c',
    date: 'August 9, 2026',
    category: 'Income Tax',
    summary: 'Five deductions that keep working once the Rs 1.5 lakh Section 80C limit is used up: NPS, health insurance, home loan interest, education loan interest, and donations.',
  },
  {
    title: 'Income Tax on Freelancers & Gig Workers in India',
    slug: 'income-tax-freelancers-gig-workers-india',
    date: 'August 10, 2026',
    category: 'Income Tax',
    summary: 'How freelance and gig income is classified for tax, presumptive taxation eligibility, advance tax obligations, client-side TDS, GST registration thresholds, and deductible expenses.',
  },
  {
    title: 'Section 87A Rebate: Zero Tax Up to This Income Limit',
    slug: 'section-87a-rebate-zero-tax-limit',
    date: 'August 10, 2026',
    category: 'Income Tax',
    summary: 'Section 87A rebate mechanics under the old and new tax regimes, marginal relief near the threshold, and the capital gains exclusion that limits who actually pays zero tax.',
  },
  {
    title: 'Set-Off and Carry Forward of Losses Under Income Tax',
    slug: 'set-off-carry-forward-losses-income-tax',
    date: 'August 11, 2026',
    category: 'Income Tax',
    summary: 'Intra-head and inter-head loss set-off rules, the house property loss set-off cap, carry-forward periods by loss type, and why filing on time is required to carry forward most losses.',
  },
  {
    title: 'Section 43B(h): MSME Payment Disallowance Rules for Buyers',
    slug: 'section-43bh-msme-payment-disallowance-buyers',
    date: 'August 11, 2026',
    category: 'Income Tax',
    summary: 'The 45-day and 15-day MSME payment rules under Section 43B(h), which suppliers count as micro or small, and how a buyer\'s unpaid year-end dues get disallowed as a deduction.',
  },
  {
    title: 'Tax Audit Under Section 44AB: Turnover Limits & Applicability FY 2026-27',
    slug: 'tax-audit-section-44ab-turnover-limits-fy-2026-27',
    date: 'August 12, 2026',
    category: 'Tax Audit',
    summary: 'Current Section 44AB tax audit turnover limits for businesses and professionals, the higher digital-transaction threshold, and how opting out of presumptive taxation triggers an audit.',
  },
  {
    title: 'Tax Audit Report Forms: 3CA vs 3CB vs 3CD Explained',
    slug: 'tax-audit-report-forms-3ca-3cb-3cd-explained',
    date: 'August 13, 2026',
    category: 'Tax Audit',
    summary: 'When Form 3CA applies versus Form 3CB, what the detailed Form 3CD statement of particulars covers, and the proposed consolidation of these forms under the new Act.',
  },
  {
    title: 'Tax Audit vs Statutory Audit vs GST Audit: Key Differences',
    slug: 'tax-audit-vs-statutory-audit-vs-gst-audit',
    date: 'August 13, 2026',
    category: 'Tax Audit',
    summary: 'Statutory audit, tax audit under Section 44AB, and GST reconciliation are three separate requirements under three separate laws, who needs which, and why a growing business often needs all three.',
  },
  {
    title: 'Due Date for Tax Audit Report Filing & Penalty for Delay',
    slug: 'tax-audit-due-date-penalty-for-delay',
    date: 'August 14, 2026',
    category: 'Tax Audit',
    summary: 'The current tax audit due date, how Form 3CA/3CB and 3CD are filed online, and the Section 271B penalty for missing the deadline.',
  },
  {
    title: 'Who Needs a Tax Audit: Business vs Professional Turnover Thresholds',
    slug: 'who-needs-tax-audit-business-professional-thresholds',
    date: 'August 15, 2026',
    category: 'Tax Audit',
    summary: 'A practical checklist for whether your business or profession needs a tax audit this year, including the presumptive-taxation escape valve and its risks.',
  },
  {
    title: 'Books of Accounts Required Under Section 44AA',
    slug: 'books-of-accounts-section-44aa',
    date: 'August 15, 2026',
    category: 'Tax Audit',
    summary: 'Which businesses and professionals must maintain books of accounts under Section 44AA, the applicable thresholds, and the penalty for failing to maintain them.',
  },
  {
    title: 'Income Tax Scrutiny Assessment: What Triggers It & How to Respond',
    slug: 'income-tax-scrutiny-assessment-how-to-respond',
    date: 'August 16, 2026',
    category: 'Tax Audit',
    summary: 'What triggers CASS selection for income tax scrutiny, how to prepare documents for a strong response, and the common mistakes that make scrutiny assessments go badly.',
  },
  {
    title: 'Best Judgment Assessment Under Section 144: What It Means',
    slug: 'best-judgment-assessment-section-144',
    date: 'August 16, 2026',
    category: 'Tax Audit',
    summary: 'When the assessing officer can proceed to a best judgment assessment, how it differs from a normal assessment, and the narrower grounds for challenging one on appeal.',
  },
  {
    title: 'Which ITR Form Should You File? ITR-1 vs ITR-2 vs ITR-3 vs ITR-4',
    slug: 'which-itr-form-to-file-itr1-itr2-itr3-itr4',
    date: 'July 22, 2026',
    category: 'Income Tax',
    summary: 'Eligibility for each ITR form, including the Rs 50 lakh/2-property/Rs 1.25 lakh LTCG limits for ITR-1, and why filing the wrong form risks a defective-return notice.',
  },
  {
    title: 'How to File ITR Online: Step-by-Step Guide for Salaried Individuals',
    slug: 'how-to-file-itr-online-salaried-guide',
    date: 'July 20, 2026',
    category: 'Income Tax',
    summary: 'Document checklist, Form 16/26AS/AIS reconciliation, ITR form and regime selection, the portal filing steps, and e-verification within the required window.',
  },
  {
    title: 'Income Tax Slabs FY 2026-27: Old Regime vs New Regime Comparison',
    slug: 'income-tax-slabs-fy-2026-27-old-vs-new-regime',
    date: 'July 21, 2026',
    category: 'Income Tax',
    summary: 'Current FY 2026-27 slab tables for both regimes, the Section 87A rebate and standard deduction math, and a practical decision framework for choosing old vs new.',
  },
  {
    title: 'Section 80C Deductions: Complete List of Eligible Investments',
    slug: 'section-80c-deductions-eligible-investments-list',
    date: 'July 24, 2026',
    category: 'Income Tax',
    summary: 'The full Rs 1.5 lakh Section 80C basket, PPF, ELSS, life insurance, NSC, tax-saver FDs, home loan principal, EPF, and tuition fees, plus what it does not cover.',
  },
  {
    title: 'House Rent Allowance (HRA) Exemption: Calculation & Documents Needed',
    slug: 'hra-exemption-calculation-documents-needed',
    date: 'July 22, 2026',
    category: 'Income Tax',
    summary: 'The least-of-three HRA exemption formula, metro vs non-metro rates, landlord PAN requirements above Rs 1 lakh/year, and why it applies only under the old regime.',
  },
  {
    title: 'Form 16 Explained: How to Read It and File Your ITR',
    slug: 'form-16-explained-how-to-read-file-itr',
    date: 'July 23, 2026',
    category: 'Income Tax',
    summary: 'What Form 16 Part A and Part B actually show, how to match it against Form 26AS and AIS, and how to use it to file your ITR correctly.',
  },
  {
    title: 'Section 80D: Health Insurance Premium Deduction Explained',
    slug: 'section-80d-health-insurance-deduction-explained',
    date: 'July 23, 2026',
    category: 'Income Tax',
    summary: 'Section 80D limits for self, family, and parents, the senior citizen enhancement, the Rs 5,000 preventive check-up sub-limit, and its old-regime-only availability.',
  },
  {
    title: 'Capital Gains Tax on Property Sale for Residents: LTCG & STCG Rates',
    slug: 'capital-gains-tax-property-sale-residents-ltcg-stcg',
    date: 'July 25, 2026',
    category: 'Income Tax',
    summary: 'The 24-month LTCG/STCG threshold, the 12.5% rate with the pre-July 2024 indexation safeguard, Section 54/54EC/54F exemptions, and Section 194-IA TDS for resident sellers.',
  },
  {
    title: 'Income From House Property: Self-Occupied vs Let-Out Taxation',
    slug: 'income-from-house-property-self-occupied-let-out',
    date: 'July 25, 2026',
    category: 'Income Tax',
    summary: 'How self-occupied and let-out properties are computed differently, the Rs 2 lakh home loan interest cap, the two-house self-occupied rule, and the house property loss set-off cap.',
  },
  {
    title: 'Capital Gains Tax on Shares & Mutual Funds: Equity vs Debt Taxation',
    slug: 'capital-gains-tax-shares-mutual-funds-equity-debt',
    date: 'July 26, 2026',
    category: 'Income Tax',
    summary: 'Resident equity vs debt fund taxation, the 12.5%/20% equity rates with the Rs 1.25 lakh exemption, and why residents face no TDS on mutual fund redemption unlike NRIs.',
  },
  {
    title: 'HUF Taxation in India: Formation, Benefits & Filing',
    slug: 'huf-taxation-india-formation-benefits-filing',
    date: 'July 26, 2026',
    category: 'Income Tax',
    summary: 'How to form an HUF, the separate exemption and deductions it unlocks as its own taxable entity, and why only a total partition ends it for tax purposes.',
  },
  {
    title: 'Clubbing of Income: When Spouse or Minor Income Is Taxed to You',
    slug: 'clubbing-of-income-spouse-minor-tax-rules',
    date: 'July 27, 2026',
    category: 'Income Tax',
    summary: 'Section 64 rules on income clubbed back to the transferor for spousal gifts and minor-child income, the skill/disability/PPF exceptions, and the cross-transfer doctrine.',
  },
  {
    title: 'Income Tax on Cryptocurrency & Virtual Digital Assets (VDA)',
    slug: 'income-tax-cryptocurrency-virtual-digital-assets-vda',
    date: 'July 27, 2026',
    category: 'Income Tax',
    summary: 'The flat 30% tax on crypto and NFT gains, 1% TDS on transfers, and the strict no-loss-set-off rule that applies to virtual digital assets.',
  },
  {
    title: 'Tax on Lottery, Game Shows & Online Gaming Winnings (Section 194BA)',
    slug: 'tax-on-lottery-game-shows-online-gaming-winnings',
    date: 'July 28, 2026',
    category: 'Income Tax',
    summary: 'The flat 30% tax on lottery and game show winnings versus the no-threshold regime for online gaming net winnings, and why no exemptions or loss set-off apply to either.',
  },
  {
    title: 'Section 56(2)(x): Tax on Gifts Received Above Rs 50,000',
    slug: 'section-56-2-x-tax-on-gifts-received-rs-50000',
    date: 'July 29, 2026',
    category: 'Income Tax',
    summary: 'The general gift-tax rule for any resident taxpayer, the full relative-exemption list, and marriage/inheritance occasion exemptions.',
  },
  {
    title: 'Advance Tax: Who Must Pay, Due Dates & Interest for Default',
    slug: 'advance-tax-who-must-pay-due-dates-interest',
    date: 'July 29, 2026',
    category: 'Income Tax',
    summary: 'Who must pay advance tax, the four cumulative quarterly instalment dates, and how interest applies on a shortfall.',
  },
  {
    title: 'Income Tax Refund Status: How to Check & Common Delays',
    slug: 'income-tax-refund-status-check-common-delays',
    date: 'July 30, 2026',
    category: 'Income Tax',
    summary: 'How to track refund status on the e-filing portal, realistic processing timelines, and the most common causes of a delayed or failed refund.',
  },
  {
    title: 'Rectification Under Section 154: Fixing Errors in Your ITR',
    slug: 'rectification-under-section-154-itr-errors',
    date: 'July 31, 2026',
    category: 'Income Tax',
    summary: 'What qualifies as a mistake apparent from the record for rectification, how it differs from filing a revised return, and the online filing process.',
  },
  {
    title: 'Income Tax Notices Explained: Section 143(1), 143(2) & 148',
    slug: 'income-tax-notices-explained-143-1-143-2-148',
    date: 'July 31, 2026',
    category: 'Income Tax',
    summary: 'What a Section 143(1) intimation, a Section 143(2) scrutiny notice, and a Section 148 reassessment notice each mean, and how to respond within the deadline.',
  },
  {
    title: 'Faceless Assessment Scheme: How It Works & What to Expect',
    slug: 'faceless-assessment-scheme-how-it-works',
    date: 'August 1, 2026',
    category: 'Income Tax',
    summary: 'How the Faceless Assessment Scheme randomly assigns cases through NFAC\'s assessment units, a typical case sequence, and how to prepare a response.',
  },
  {
    title: 'Condonation of Delay in Filing ITR: When & How to Apply',
    slug: 'condonation-of-delay-filing-itr-how-to-apply',
    date: 'August 1, 2026',
    category: 'Income Tax',
    summary: 'Who can apply for condonation of delay to claim a refund or carry-forward loss after missing the deadline, the monetary-limit table, and the 5-year application window.',
  },
  {
    title: 'Belated, Revised & Updated Returns: ITR-U Under Section 139(8A)',
    slug: 'belated-revised-updated-returns-itr-u-139-8a',
    date: 'August 2, 2026',
    category: 'Income Tax',
    summary: 'The three correction routes for an ITR, belated, revised, and updated (ITR-U), with the extended filing window, step-up additional tax slabs, and who is barred from filing ITR-U.',
  },
  {
    title: 'Presumptive Taxation Scheme Section 44AD: Eligibility & Benefits',
    slug: 'presumptive-taxation-scheme-section-44ad',
    date: 'August 2, 2026',
    category: 'Income Tax',
    summary: 'Section 44AD eligibility, turnover limits for cash vs digital receipts, the deemed profit rates, and the 5-year lock-in penalty for opting out.',
  },
  {
    title: 'Presumptive Taxation for Professionals: Section 44ADA Explained',
    slug: 'presumptive-taxation-professionals-section-44ada',
    date: 'August 3, 2026',
    category: 'Income Tax',
    summary: 'Section 44ADA eligibility for specified professionals, the gross receipts limits, and the flat 50% deemed profit rate, contrasted against the 44AD scheme for traders.',
  },
  {
    title: 'Presumptive Taxation for Transporters: Section 44AE',
    slug: 'presumptive-taxation-transporters-section-44ae',
    date: 'August 3, 2026',
    category: 'Income Tax',
    summary: 'The Section 44AE deemed-income scheme for owners of up to 10 goods vehicles, with separate rates for heavy and other goods vehicles.',
  },
  {
    title: 'TDS on Salary: Section 192 & Form 24Q Explained',
    slug: 'tds-on-salary-section-192-form-24q',
    date: 'August 5, 2026',
    category: 'Income Tax',
    summary: 'How employers compute average-rate TDS on salary, handle old vs new regime declarations, and file the quarterly salary TDS return.',
  },
  {
    title: 'TDS on Rent Under Section 194-IB: When Tenants Must Deduct',
    slug: 'tds-on-rent-section-194ib-tenants-deduct',
    date: 'August 5, 2026',
    category: 'Income Tax',
    summary: 'When individual and HUF tenants not liable for audit must deduct TDS on rent above the monthly threshold, filed once yearly via Form 26QC with no TAN required.',
  },
  {
    title: 'TDS on Professional & Technical Fees: Section 194J Explained',
    slug: 'tds-professional-technical-fees-section-194j',
    date: 'August 6, 2026',
    category: 'Income Tax',
    summary: 'Section 194J TDS rates for professional versus technical services, the per-category threshold, and the higher no-PAN rate.',
  },
  {
    title: 'TDS on Contractor Payments: Section 194C Compliance Guide',
    slug: 'tds-contractor-payments-section-194c-guide',
    date: 'August 6, 2026',
    category: 'Income Tax',
    summary: 'Section 194C TDS rates for individual/HUF versus other deductees, the per-payment and aggregate thresholds, and the small-transporter exemption.',
  },
  {
    title: 'Section 194Q: TDS on Purchase of Goods Above Rs 50 Lakh',
    slug: 'section-194q-tds-purchase-of-goods',
    date: 'August 7, 2026',
    category: 'Income Tax',
    summary: 'Buyer-side TDS on goods purchases above Rs 50 lakh from a resident seller, the turnover condition, and why the old overlap with Section 206C(1H) TCS no longer applies.',
  },
  {
    title: 'GST Audit: Applicability & What Auditors Check',
    slug: 'gst-audit-applicability-guide',
    date: 'July 21, 2026',
    category: 'GST',
    summary: 'GSTR-9C reconciliation applicability above Rs 5 crore turnover, the current self-certification position, and what a Section 65 departmental audit or Section 66 special audit actually examines.',
  },
  {
    title: 'GST Registration Cancellation & Revocation: Process & Grounds',
    slug: 'gst-registration-cancellation-revocation',
    date: 'July 19, 2026',
    category: 'GST',
    summary: 'The grounds for GST cancellation under Rule 21, the difference between voluntary and officer-initiated cancellation, and the Rule 23 revocation process, timeline, and what happens if you miss the window.',
  },
  {
    title: 'Letter of Undertaking (LUT) for GST-Free Exports: How to File',
    slug: 'lut-letter-undertaking-gst-exports',
    date: 'July 19, 2026',
    category: 'GST',
    summary: 'Form GST RFD-11 eligibility, the step-by-step LUT filing process on the GST portal, its one-financial-year validity, and the cost of exporting without a valid LUT in place.',
  },
  {
    title: 'GST Late Fees & Interest: How They Are Calculated',
    slug: 'gst-late-fees-interest-calculation',
    date: 'July 20, 2026',
    category: 'GST',
    summary: 'Section 47 late fees (nil vs non-nil, turnover-based caps) and Section 50 interest calculated on the cash-ledger portion of tax, with a worked delay example.',
  },
  {
    title: 'GST for E-Commerce Sellers: TCS Under Section 52 & Registration',
    slug: 'gst-for-ecommerce-sellers-tcs-section-52',
    date: 'July 17, 2026',
    category: 'GST',
    summary: 'Mandatory GST registration for marketplace goods sellers regardless of turnover, the Section 52 TCS mechanism, GSTR-8 credit reconciliation, and why the composition scheme is not available to these sellers.',
  },
  {
    title: 'GST on Works Contract Services: Rate & ITC Rules',
    slug: 'gst-works-contract-services-rate-itc',
    date: 'July 17, 2026',
    category: 'GST',
    summary: 'The GST rate on works contract services and why Section 17(5)(c)/(d) blocks input tax credit for a business constructing its own immovable property, versus a contractor making a further taxable supply.',
  },
  {
    title: 'GST on Real Estate: Under-Construction vs Ready-to-Move Properties',
    slug: 'gst-on-real-estate-under-construction-ready',
    date: 'July 18, 2026',
    category: 'GST',
    summary: 'Why ready-to-move properties are GST-free but under-construction flats attract 1% or 5% GST without ITC, and how affordable housing is defined.',
  },
  {
    title: 'E-Invoicing Under GST: Applicability Threshold & Process',
    slug: 'e-invoicing-gst-applicability-threshold',
    date: 'July 15, 2026',
    category: 'GST',
    summary: 'Who must generate e-invoices under GST, the Rs 5 crore turnover trigger, the IRN/QR code process, and the 30-day reporting rule for larger taxpayers.',
  },
  {
    title: 'E-Way Bill Rules: When Required, Validity & Penalties',
    slug: 'e-way-bill-rules-validity-penalties',
    date: 'July 16, 2026',
    category: 'GST',
    summary: 'When an e-way bill is mandatory, the Rs 50,000 threshold, distance-based validity, extension limits, and penalties for moving goods without one.',
  },
  {
    title: 'Reverse Charge Mechanism (RCM) Under GST: When It Applies',
    slug: 'reverse-charge-mechanism-rcm-gst',
    date: 'July 16, 2026',
    category: 'GST',
    summary: 'How RCM shifts GST liability to the recipient for notified categories like GTA freight, legal services, and director services, the self-invoicing and cash-payment requirements, and ITC availability on RCM tax paid.',
  },
  {
    title: 'Input Tax Credit (ITC) Under GST: Eligibility, Reversal & Blocked Credits',
    slug: 'input-tax-credit-itc-gst-guide',
    date: 'July 14, 2026',
    category: 'GST',
    summary: 'The four conditions to claim ITC, the Section 16(4) claim deadline, the Rule 37 180-day supplier-payment reversal rule, and the full Section 17(5) blocked-credit list.',
  },
  {
    title: 'GSTR-9 & GSTR-9C: Annual Return and Reconciliation Guide',
    slug: 'gstr-9-gstr-9c-annual-return-guide',
    date: 'July 14, 2026',
    category: 'GST',
    summary: 'GSTR-9 kicks in above Rs 2 crore turnover and GSTR-9C above Rs 5 crore, both due December 31; applicability, the self-certification change, and how the two forms reconcile against your books.',
  },
  {
    title: 'GSTR-1 vs GSTR-3B: Filing Guide & Common Mistakes',
    slug: 'gstr-1-vs-gstr-3b-filing-guide',
    date: 'July 15, 2026',
    category: 'GST',
    summary: 'What GSTR-1 and GSTR-3B each report, monthly vs QRMP due dates, late fees and interest, and the reconciliation mistakes between the two returns that most commonly trigger GST department notices.',
  },
  {
    title: 'GST Composition Scheme: Eligibility, Rates & When to Opt In',
    slug: 'gst-composition-scheme-eligibility-rates',
    date: 'September 17, 2026',
    category: 'GST',
    summary: 'Turnover eligibility and flat tax rates under the GST composition scheme for traders, restaurants, and services, plus CMP-08/GSTR-4 filing and a practical framework for deciding whether it benefits a small business.',
  },
  {
    title: 'GST Registration Process in India: Complete Guide for New Businesses',
    slug: 'gst-registration-process-india-guide',
    date: 'September 17, 2026',
    category: 'GST',
    summary: 'Who must register for GST, turnover thresholds for goods vs services, compulsory-registration triggers under Section 24, documents, the online process, and multi-state registration for new businesses.',
  },
  {
    title: 'Startup Advisory for Foreign Investors Investing in India',
    slug: 'startup-advisory-foreign-investors-india',
    date: 'September 16, 2026',
    category: 'Startup Advisory',
    summary: 'Entry route and FDI pricing checks, due diligence on cap table and compliance history, valuation certification, and FC-GPR/FLA reporting oversight for foreign investors backing an Indian startup.',
  },
  {
    title: 'Comparable Uncontrolled Price (CUP) Method: India Transfer Pricing Guide',
    slug: 'comparable-uncontrolled-price-method-cup-india',
    date: 'September 16, 2026',
    category: 'Transfer Pricing',
    summary: 'Internal vs external CUP, when it fits intra-group loans, royalties, and commodity transactions, comparability adjustments, and a worked loan-pricing example.',
  },
  {
    title: 'Resale Price Method (RPM) in Transfer Pricing: India Guide',
    slug: 'resale-price-method-transfer-pricing-india',
    date: 'September 15, 2026',
    category: 'Transfer Pricing',
    summary: 'When RPM fits a routine distributor, the gross margin calculation, why accounting-classification differences undermine it, and a worked example.',
  },
  {
    title: 'TNMM: Transactional Net Margin Method Explained (India)',
    slug: 'tnmm-transactional-net-margin-method-india',
    date: 'September 14, 2026',
    category: 'Transfer Pricing',
    summary: 'Why TNMM is the default method for Indian captive service providers, profit level indicators, comparable selection, and a worked margin example.',
  },
  {
    title: 'Can an NRI Buy Agricultural Land in India? FEMA Rules, Exceptions & the FDI/ODI Angle',
    slug: 'nri-agricultural-land-india-fema-rules',
    date: 'September 10, 2026',
    category: 'NRI Taxation',
    summary: 'The FEMA restriction on NRIs and OCIs purchasing agricultural land, the inheritance and gift exceptions, resale rules, penalties for breach, and why FDI/ODI structures don\'t offer a workaround.',
  },
  {
    title: 'FDI in India: Routes, Sectoral Rules & Compliance Guide',
    slug: 'fdi-in-india-routes-compliance-guide',
    date: 'September 7, 2026',
    category: 'FEMA & Compliance',
    summary: 'Automatic route vs government route, sectoral caps, the Press Note 3 land-border rule, pricing guidelines, and FC-GPR/FC-TRS reporting for FDI into India.',
  },
  {
    title: 'Overseas Direct Investment (ODI): Rules & Compliance Guide',
    slug: 'odi-overseas-direct-investment-guide-india',
    date: 'September 4, 2026',
    category: 'FEMA & Compliance',
    summary: 'Who can make an ODI, ODI vs OPI, the automatic and approval routes, FIRMS/APR reporting, and the one-year holding rule under the FEMA Overseas Investment framework.',
  },
  {
    title: 'FAST-DS 2026: Foreign Assets Disclosure Scheme Explained',
    slug: 'fast-ds-2026-foreign-assets-disclosure-scheme',
    date: 'September 1, 2026',
    category: 'Tax Compliance',
    summary: 'Eligibility, the Rs 1 crore asset limit, the 30%+30% tax structure, the December 31, 2026 declaration window, and the protection it gives under the Black Money Act.',
  },
  {
    title: 'Startup Compliance Automation: RBI ODI, APR, Transfer Pricing & GST',
    slug: 'startup-compliance-automation-odi-apr-gst',
    date: 'September 8, 2026',
    category: 'Startup Advisory',
    summary: 'How growing India-linked startups organise RBI ODI reporting, annual APR filing, transfer pricing documentation, and GST workflows; and where a virtual CFO or offshore accounting team fits in.',
  },
  {
    title: 'Form 27Q: Complete TDS Return Filing Guide for Payments to NRIs',
    slug: 'form-27q-tds-return-filing-guide',
    date: 'September 8, 2026',
    category: 'NRI Taxation',
    summary: 'Who must file Form 27Q, quarterly due dates, return structure, correction statements, penalties, and how it differs from Form 27QB for property purchases.',
  },
  {
    title: 'NRO Account TDS Refund: How to Claim Back Excess Tax Deducted',
    slug: 'nro-tds-refund-claim-process',
    date: 'September 8, 2026',
    category: 'NRI Taxation',
    summary: 'Which ITR to file, Form 26AS reconciliation, documents needed, and how the USD 1 million repatriation limit applies once the refund lands in your NRO account.',
  },
  {
    title: 'NRI GAAR Exposure: When Anti-Avoidance Rules Apply to Cross-Border Structures',
    slug: 'nri-gaar-cross-border-structures',
    date: 'August 22, 2026',
    category: 'International Tax',
    summary: 'The Impermissible Avoidance Arrangement test, the Rs 3 crore tax benefit threshold under Rule 10U, and common NRI cross-border scenarios that attract GAAR scrutiny.',
  },
  {
    title: 'India-UAE Transfer Pricing: Compliance for Cross-Border Transactions',
    slug: 'india-uae-transfer-pricing-compliance',
    date: 'August 16, 2026',
    category: 'Transfer Pricing',
    summary: 'Dual compliance since UAE Corporate Tax, DTAA Article 9 relief, Free Zone considerations, and common India-UAE transaction scenarios.',
  },
  {
    title: 'TP Audit: How to Handle a Transfer Pricing Assessment in India',
    slug: 'transfer-pricing-audit-assessment-india',
    date: 'August 15, 2026',
    category: 'Transfer Pricing',
    summary: 'Selection triggers, the assessment sequence, show-cause notice strategy, DRP vs CIT(Appeals), and MAP for double taxation.',
  },
  {
    title: 'NRI Tax Compliance Calendar: Every Deadline (FY 2026-27)',
    slug: 'nri-tax-compliance-calendar-deadlines',
    date: 'August 14, 2026',
    category: 'NRI Taxation',
    summary: 'Advance tax, ITR filing, Form 27Q, Form 145/146, and every other deadline NRIs need to track.',
  },
  {
    title: 'Startup Compliance Calendar: Year 1 to Year 3 Checklist',
    slug: 'startup-compliance-calendar-year-1-3',
    date: 'August 13, 2026',
    category: 'Startup Advisory',
    summary: 'Month-by-month and year-by-year compliance roadmap: GST, TDS, MCA filings, advance tax, FEMA reporting, ESOP, and DPIIT self-certification.',
  },
  {
    title: 'Post-Incorporation Checklist: First 30 Days After Company Registration',
    slug: 'post-incorporation-checklist-first-30-days',
    date: 'August 12, 2026',
    category: 'Company Incorporation',
    summary: 'PAN/TAN, bank account, GST, first Board meeting, auditor appointment, and share certificates; with statutory deadlines.',
  },
  {
    title: 'India DTAA Guide for NRIs by Country: US, UK, UAE, Canada, Australia, Singapore',
    slug: 'dtaa-guide-nri-country-wise',
    date: 'August 11, 2026',
    category: 'International Tax',
    summary: 'Treaty rates for 6 key NRI corridors, TRC and Form 10F process, and foreign tax credit claims.',
  },
  {
    title: 'Master File vs Local File vs CbCR: What Indian Subsidiaries Must Prepare',
    slug: 'master-file-local-file-cbcr-india',
    date: 'August 10, 2026',
    category: 'Transfer Pricing',
    summary: 'Thresholds and content for the three-tier TP documentation structure: Master File (Rs 500cr), Local File, and CbCR (Rs 5,500cr).',
  },
  {
    title: 'Form 3CEB: Due Date, Filing Process & Penalties (FY 2026-27)',
    slug: 'form-3ceb-transfer-pricing-audit-report',
    date: 'August 9, 2026',
    category: 'Transfer Pricing',
    summary: 'Who must file, the October 31 due date, the e-filing process, and the Rs 1 lakh penalty under Section 271BA.',
  },
  {
    title: 'Foreign Retirement Fund Taxation: 401(k), UK Pension & Superannuation',
    slug: 'foreign-retirement-fund-taxation-nri',
    date: 'August 6, 2026',
    category: 'NRI Taxation',
    summary: 'How India taxes US 401(k), UK pension, and Australian super withdrawals. RNOR window strategy, DTAA relief, and timing decisions.',
  },
  {
    title: 'Transfer Pricing for IT Services Companies in India',
    slug: 'transfer-pricing-it-services-india',
    date: 'August 7, 2026',
    category: 'Transfer Pricing',
    summary: 'Why TNMM is the default method for captive IT/ITES providers, limited-risk vs entrepreneur profiles, and common TPO disputes.',
  },
  {
    title: 'Advance Pricing Agreement (APA) India: Process, Timeline & Benefits',
    slug: 'advance-pricing-agreement-apa-india',
    date: 'August 5, 2026',
    category: 'Transfer Pricing',
    summary: 'Unilateral vs bilateral vs multilateral APAs, the application process, realistic timelines, and a cost-benefit framework.',
  },
  {
    title: 'Due Diligence Checklist for Startup Fundraising',
    slug: 'due-diligence-checklist-startup-fundraising',
    date: 'August 4, 2026',
    category: 'Startup Advisory',
    summary: 'Corporate records, cap table reconciliation, IP ownership, material contracts, and a data room preparation timeline.',
  },
  {
    title: 'Safe Harbour Rules for Transfer Pricing in India (2026)',
    slug: 'safe-harbour-rules-transfer-pricing-india',
    date: 'August 3, 2026',
    category: 'Transfer Pricing',
    summary: 'Eligible categories (software development, ITES, KPO, loans, guarantees), how to opt in via Form 3CEFA, and the lock-in trade-off.',
  },
  {
    title: 'GST Registration for Startups: When Required & First Return Guide',
    slug: 'gst-registration-startups-first-return',
    date: 'August 2, 2026',
    category: 'Startup Advisory',
    summary: 'Turnover thresholds, compulsory registration triggers, the registration process, and your first GSTR-1/GSTR-3B.',
  },
  {
    title: 'NRI Returning to India: Complete Financial Checklist (2026)',
    slug: 'nri-returning-india-financial-checklist',
    date: 'August 1, 2026',
    category: 'NRI Taxation',
    summary: 'Bank account conversion, RNOR planning, investment restructuring, insurance, and FEMA steps for NRIs moving back to India.',
  },
  {
    title: 'Founder Agreement Essentials for Indian Startups',
    slug: 'founder-agreement-essentials-indian-startups',
    date: 'July 31, 2026',
    category: 'Startup Advisory',
    summary: 'Equity split rationale, founder reverse vesting, IP assignment, non-compete enforceability, and exit mechanisms.',
  },
  {
    title: 'Transfer Pricing Methods Explained: CUP, TNMM, RPM, CPM & PSM',
    slug: 'transfer-pricing-methods-india-explained',
    date: 'July 30, 2026',
    category: 'Transfer Pricing',
    summary: 'What each of the 5 prescribed methods tests, when it is the most appropriate method, and a worked TNMM example.',
  },
  {
    title: 'Schedule FA: Foreign Asset Disclosure for Returning Indians',
    slug: 'schedule-fa-foreign-asset-disclosure-nri',
    date: 'July 28, 2026',
    category: 'NRI Taxation',
    summary: 'When Schedule FA kicks in (Resident/RNOR only), what to declare, and Rs 10 lakh penalty for non-disclosure.',
  },
  {
    title: 'Convertible Notes vs Equity: FEMA Rules for Indian Startups',
    slug: 'convertible-notes-vs-equity-fema-startups',
    date: 'July 27, 2026',
    category: 'Startup Advisory',
    summary: 'When a convertible note, CCPS, or straight equity is the right instrument, and the FEMA conditions that apply.',
  },
  {
    title: 'Startup Valuation in India: Methods, When Required & Who Can Do It',
    slug: 'startup-valuation-methods-india',
    date: 'July 24, 2026',
    category: 'Startup Advisory',
    summary: 'DCF, NAV, and comparables explained, when valuation is legally required, and who can issue a valid report.',
  },
  {
    title: 'NRI ITR Filing Guide: Which Form, How to File from Abroad',
    slug: 'nri-itr-filing-guide-from-abroad',
    date: 'July 22, 2026',
    category: 'NRI Taxation',
    summary: 'ITR-2 vs ITR-3, documents needed, e-verification without Aadhaar, filing deadline, and common mistakes.',
  },
  {
    title: 'Angel Tax (Section 56(2)(viib)): Abolished for All Investors from FY 2024-25',
    slug: 'angel-tax-section-56-share-premium-startups',
    date: 'July 21, 2026',
    category: 'Startup Advisory',
    summary: 'What the abolition of angel tax means for new fundraising, and why historic rounds still need review.',
  },
  {
    title: 'NRI Selling Shares in an Indian Private Company: Tax & FEMA Compliance',
    slug: 'nri-selling-shares-indian-private-company-tax-fema',
    date: 'July 20, 2026',
    category: 'NRI Taxation',
    summary: 'FEMA pricing guidelines and valuation, TDS under Section 393(2), capital gains treatment, and FC-TRS reporting for an NRI exiting a private company.',
  },
  {
    title: 'ESOP Structuring for Indian Startups: Scheme Design, Vesting & Tax',
    slug: 'esop-structuring-indian-startups',
    date: 'July 17, 2026',
    category: 'Startup Advisory',
    summary: 'Pool sizing, vesting schedules, exercise price, Companies Act mechanics, and the two-stage employee tax.',
  },
  {
    title: 'NRI Mutual Fund & Stock Taxation in India (FY 2026-27)',
    slug: 'nri-mutual-fund-stock-taxation-india',
    date: 'July 16, 2026',
    category: 'NRI Taxation',
    summary: 'LTCG/STCG rates, TDS on redemption, PIS account for direct equity, and FATCA restrictions for US/Canada NRIs.',
  },
  {
    title: 'NRI Rental Income Tax in India: TDS, Deductions & Filing',
    slug: 'nri-rental-income-tax-india',
    date: 'July 14, 2026',
    category: 'NRI Taxation',
    summary: '30% TDS by tenant, standard deduction, home loan interest, ITR refund process, and Form 13 for NRI landlords.',
  },
  {
    title: 'TDS on NRO Account Interest and FD: Rates & DTAA Relief',
    slug: 'tds-nro-interest-fd-dtaa-relief',
    date: 'July 8, 2026',
    category: 'NRI Taxation',
    summary: '30% TDS on NRO interest and how to cut it to 10-15% with DTAA treaty rates using TRC and Form 10F.',
  },
  {
    title: 'Company Name Reservation in India: SPICe+ Part A & RUN Explained',
    slug: 'company-name-reservation-run-form-india',
    date: 'July 6, 2026',
    category: 'Company Incorporation',
    summary: 'SPICe+ Part A vs the RUN service, MCA naming guidelines, common rejection reasons, and why a trademark search matters before you file.',
  },
  {
    title: 'NRO Account Repatriation: Rules, USD 1 Million Limit & Step-by-Step Process',
    slug: 'nro-account-repatriation-rules-process',
    date: 'July 4, 2026',
    category: 'NRI Taxation',
    summary: 'How to repatriate from an NRO account: USD 1 million annual limit, Form 145/146 process, documents needed, and common bank rejections.',
  },
  {
    title: 'DSC and DIN Application: A Practical Guide for Directors',
    slug: 'dsc-din-application-director-guide',
    date: 'July 2, 2026',
    category: 'Company Incorporation',
    summary: 'Digital Signature Certificate process, DIN allotment via SPICe+ for new companies vs Form DIR-3 for existing companies, and common rejection reasons.',
  },
  {
    title: 'Form 15CA & 15CB (Now 145 & 146): NRI Remittance Compliance Guide',
    slug: 'form-15ca-15cb-nri-remittance-guide',
    date: 'June 27, 2026',
    category: 'NRI Taxation',
    summary: 'The 4 parts of Form 15CA, when CA certificate (15CB) is needed, step-by-step filing, and what happens if you skip it.',
  },
  {
    title: 'OPC to Private Limited Company Conversion: A Founder\'s Guide',
    slug: 'opc-to-private-limited-conversion-india',
    date: 'June 26, 2026',
    category: 'Company Incorporation',
    summary: 'When OPC conversion becomes mandatory, when it is a strategic choice, and the step-by-step MCA conversion process.',
  },
  {
    title: 'Foreign Subsidiary Registration in India: FDI Route and Compliance Guide',
    slug: 'foreign-subsidiary-registration-india-fdi',
    date: 'June 23, 2026',
    category: 'Company Incorporation',
    summary: 'Automatic vs Government FDI route, the resident director requirement, SPICe+ for foreign shareholders, and FC-GPR/FLA compliance.',
  },
  {
    title: 'LRS (Liberalised Remittance Scheme): USD 250K Limit & TCS',
    slug: 'lrs-liberalised-remittance-scheme-guide',
    date: 'June 20, 2026',
    category: 'FEMA & Compliance',
    summary: 'USD 250,000 annual limit, permitted purposes, TCS rates (5-20%), Form A2, and how LRS affects NRI families.',
  },
  {
    title: 'Annual ROC Filing for Private Limited Companies: AOC-4, MGT-7 and DIR-3 KYC',
    slug: 'annual-roc-filing-aoc4-mgt7-dir3-kyc',
    date: 'June 18, 2026',
    category: 'Company Incorporation',
    summary: 'Deadlines for AOC-4, MGT-7/MGT-7A, DIR-3 KYC and ADT-1, a compliance calendar around your AGM, and why late ROC filing gets expensive.',
  },
  {
    title: 'LLP vs Private Limited Company: Which Structure Fits Your Business?',
    slug: 'llp-vs-private-limited-comparison-india',
    date: 'June 15, 2026',
    category: 'Company Incorporation',
    summary: 'Tax treatment, compliance burden, fundraising limitations, and the Section 366 conversion path from LLP to Private Limited.',
  },
  {
    title: 'Section 195 TDS on Payments to NRIs: Complete Guide (FY 2026-27)',
    slug: 'section-195-tds-nri-payments-guide',
    date: 'June 12, 2026',
    category: 'NRI Taxation',
    summary: 'When and how to deduct TDS under Section 195 on payments to NRIs: property sale, rent, professional fees, interest. Rate table, TAN requirement, Form 27Q filing, and penalties.',
  },
  {
    title: 'NRI Selling Property Below Stamp Duty Value: Section 78 (Earlier Section 50C) Explained',
    slug: 'nri-property-sale-below-stamp-duty-value-section-50c',
    date: 'June 10, 2026',
    category: 'NRI Taxation',
    summary: 'The deemed full value of consideration rule when an NRI sells below circle rate, the safe harbour tolerance, and the buyer\'s separate deemed-gift exposure under Section 92.',
  },
  {
    title: '26QB vs 27Q: Which TDS Form When Buying Property from an NRI?',
    slug: '26qb-vs-27q-nri-property-tds',
    date: 'June 5, 2026',
    category: 'NRI Taxation',
    summary: 'Form 26QB is for resident sellers, Form 27Q is for NRI sellers. Side-by-side comparison: rates, TAN, filing process, and the penalty for using the wrong form.',
  },
  {
    title: 'NRI Gift & Inheritance Tax: What Is Taxable and What Is Not',
    slug: 'nri-gift-inheritance-tax-rules',
    date: 'May 29, 2026',
    category: 'NRI Taxation',
    summary: 'Inheritance (not taxable), gifts from relatives (exempt), gifts from non-relatives (Rs 50K threshold), and FEMA compliance.',
  },
  {
    title: 'Aadhaar-PAN Linking for NRIs Who Never Had an Aadhaar Number',
    slug: 'aadhaar-pan-linking-nri-without-aadhaar',
    date: 'May 22, 2026',
    category: 'NRI Taxation',
    summary: 'Who is statutorily exempt from PAN-Aadhaar linking, what an inoperative PAN means in practice, and what NRIs without Aadhaar should actually do.',
  },
  {
    title: 'NRI Residential Status: How the 182-Day and 120-Day Rules Work',
    slug: 'nri-residential-status-182-day-rule',
    date: 'May 15, 2026',
    category: 'NRI Taxation',
    summary: 'How to determine if you are NRI, RNOR, or Resident: the 182-day rule, the 120-day deemed resident rule, and what each status means for your taxes.',
  },
  {
    title: 'TCS on Foreign Remittance Under LRS: Rates & Exemptions FY 2026-27',
    slug: 'tcs-foreign-remittance-lrs-rates-fy2026-27',
    date: 'April 25, 2026',
    category: 'FEMA & Compliance',
    summary: 'The Rs 10 lakh threshold, 0% for loan-funded education, 2% for self-funded education/medical/tour packages, and 20% for other purposes after the Budget 2026 revision.',
  },
  {
    title: 'PAN Card for NRIs: Application, Aadhaar Linking & Exemptions',
    slug: 'pan-card-nri-application-aadhaar-linking',
    date: 'April 18, 2026',
    category: 'NRI Taxation',
    summary: 'How to apply from abroad (Form 49A/49AA), Aadhaar-PAN linking exemption, and why no-PAN means 20% TDS.',
  },
  {
    title: 'RNOR Status for Returning NRIs: How Long Does the Tax Holiday Last?',
    slug: 'rnor-status-tax-guide-returning-nris',
    date: 'August 8, 2026',
    category: 'NRI Taxation',
    summary: 'The two RNOR tests, how many tax-free years returning NRIs actually get, what foreign income stays exempt, and the planning checklist before RNOR status ends.',
  },
  {
    title: 'POEM: When Does a Foreign Company Become an Indian Tax Resident?',
    slug: 'poem-place-of-effective-management-india',
    date: 'August 8, 2026',
    category: 'International Tax',
    summary: 'Place of Effective Management explained: the ABOI test, the Rs 50 crore exemption, and how Indian promoters accidentally trigger Indian residency for a UAE entity.',
  },
  {
    title: 'NRE vs NRO Account: FEMA Repatriation Limits Explained',
    slug: 'nre-vs-nro-account-fema-repatriation-limits',
    date: 'August 8, 2026',
    category: 'NRI Taxation',
    summary: 'Which income goes into which account, tax treatment, the USD 1 million repatriation cap, and the FEMA mistakes that get NRI remittances frozen.',
  },
  {
    title: 'ESOP Taxation for NRIs: Exercise, Sale & DTAA Relief',
    slug: 'esop-taxation-for-nris-india',
    date: 'August 8, 2026',
    category: 'NRI Taxation',
    summary: 'Perquisite tax at exercise, capital gains at sale, the startup TDS deferral, and how to avoid double taxation on ESOPs under DTAA.',
  },
  {
    title: 'DPIIT Registration for Startups: Eligibility, Process & 80-IAC Tax Benefit (2026)',
    slug: 'dpiit-registration-startups-india-80iac',
    date: 'July 25, 2026',
    category: 'Startup Compliance',
    summary: 'How to get DPIIT recognition, what eligibility criteria apply, the 80-IAC three-year tax holiday and why it requires a separate IMB application, and what changed on angel tax in Finance Act 2025.',
  },
  {
    title: 'GST on Exports: Zero-Rated vs Exempt; What Indian Exporters Get Wrong',
    slug: 'gst-on-exports-zero-rated-vs-exempt-india',
    date: 'July 18, 2026',
    category: 'GST',
    summary: 'The difference between zero-rated and exempt supplies, why it matters for ITC claims, how to file a Letter of Undertaking (LUT), and the five conditions for export of services under GST.',
  },
  {
    title: 'Transfer Pricing Documentation Checklist for Indian Subsidiaries (2026)',
    slug: 'transfer-pricing-documentation-checklist-india',
    date: 'July 11, 2026',
    category: 'International Tax',
    summary: 'Complete TP documentation checklist: Form 3CEB vs Local File vs Master File thresholds, due dates, benchmarking requirements, and the documentation gaps that trigger transfer pricing audits.',
  },
  {
    title: 'TDS on NRI Property Sale in India (FY 2026-27): Rates, Form 27Q & Refund Guide',
    slug: 'tds-on-nri-property-sale-india',
    date: 'July 1, 2026',
    category: 'NRI Taxation',
    summary: 'Full TDS rate table with surcharge slabs, the buyer\'s TAN and Form 27Q process, Form 13 lower deduction certificates, how NRIs claim a TDS refund, and repatriation under the new Income Tax Act 2025.',
  },
  {
    title: 'Form 13 Lower Deduction Certificate for NRIs: Process, Documents & Timeline',
    slug: 'form-13-lower-deduction-certificate-nri',
    date: 'July 11, 2026',
    category: 'NRI Taxation',
    summary: 'How NRIs apply for a Form 13 lower or nil TDS certificate under Section 197 before a property sale; documents required, jurisdictional AO, and processing timeline.',
  },
  {
    title: 'How NRIs Can Claim a TDS Refund on Property Sale in India',
    slug: 'nri-tds-refund-property-sale',
    date: 'July 11, 2026',
    category: 'NRI Taxation',
    summary: 'Which ITR to file, documents needed, e-verification options, refund timelines, and Section 244A interest for NRIs recovering excess TDS on a property sale.',
  },
  {
    title: 'TAN Application Guide for Buyers Purchasing Property from an NRI',
    slug: 'tan-application-guide-buyer-nri-property',
    date: 'July 11, 2026',
    category: 'NRI Taxation',
    summary: 'Form 49B process, documents, fees, and timeline for buyers who need a TAN to purchase property from an NRI seller under Section 195.',
  },
  {
    title: 'Repatriating NRI Property Sale Proceeds: Form 145/146 & USD 1 Million Scheme',
    slug: 'nri-repatriation-property-sale-proceeds',
    date: 'July 11, 2026',
    category: 'NRI Taxation',
    summary: 'NRO account rules, Form 145 (ex-15CA), Form 146 (ex-15CB) CA certification, and the USD 1 million scheme for repatriating Indian property sale proceeds.',
  },
  {
    title: 'Capital Gains Tax for NRIs on Inherited or Gifted Property in India',
    slug: 'nri-capital-gains-inherited-gifted-property',
    date: 'July 11, 2026',
    category: 'NRI Taxation',
    summary: 'Cost and holding period carryover rules from the original owner, TDS implications, and why Form 13 is especially valuable for inherited or gifted property sales.',
  },
  {
    title: 'FEMA Compliance for Indian Startups Raising Foreign Investment (2026 Guide)',
    slug: 'fema-compliance-foreign-investment-startups',
    date: 'June 08, 2026',
    category: 'Startup Compliance',
    summary: 'FDI routes, the 30-day RBI reporting window, FC-GPR filing, the annual FLA return, and the most common FEMA mistakes that lead to penalties; a practical checklist for funded startups.',
  },
  {
    title: 'Dubai Company Registration: Complete Guide for Indian Entrepreneurs (2026)',
    slug: 'dubai-company-registration-guide',
    date: 'May 19, 2026',
    category: 'International Tax',
    summary: 'Mainland vs Free Zone vs Offshore, real costs in INR, FEMA and ODI compliance, UAE Corporate Tax, and documents required; everything before you register a Dubai company.',
  },
  {
    title: 'How to Incorporate a Company in India: Private Limited vs LLP vs OPC (2026 Guide)',
    slug: 'company-incorporation-india-guide',
    date: 'May 08, 2026',
    category: 'Corporate Law',
    summary: 'Complete guide to company registration in India, which structure to choose, the step-by-step process, what it costs, documents required, and mistakes to avoid.',
  },
  {
    title: 'UAE Entity Setup: When It Makes Sense (And When It Doesn\'t)',
    slug: 'uae-entity-setup-when-it-makes-sense',
    date: 'May 08, 2026',
    category: 'International Tax',
    summary: 'Formation costs ₹3–6L, ongoing compliance, and FEMA exposure: here\'s the honest breakdown of when a Dubai company actually works for Indian businesses, and when it\'s expensive FOMO.',
  },
  {
    title: 'Deciphering the New Income Tax Act & Rules 2025',
    slug: 'new-income-tax-act-rules-2025',
    date: 'March 20, 2026',
    category: 'Tax Reform',
    summary: 'An in-depth look at the proposed structural changes in the Income Tax Act, focusing on simplification and the new computational rules.',
  },
  {
    title: 'Understanding the New Tax Regime (FY 2025-26)',
    slug: 'understanding-new-tax-regime-2025-26',
    date: 'March 18, 2026',
    category: 'Tax Planning',
    summary: 'A detailed breakdown of the recent changes in the Finance Act and how it affects middle-income earners in India.',
  },
  {
    title: 'Essential Compliance for Indian Startups',
    slug: 'essential-compliance-indian-startups',
    date: 'March 12, 2026',
    category: 'Corporate Law',
    summary: 'Navigating the complex landscape of MCA filings, GST returns, and initial FEMA compliance for newly incorporated entities.',
  },
  {
    title: 'UAE Corporate Tax: Impact on Indian Businesses',
    slug: 'uae-corporate-tax-indian-impact',
    date: 'March 08, 2026',
    category: 'International Tax',
    summary: 'With the implementation of Corporate Tax in UAE, how should Indian businesses with Gulf operations restructure their holdings?',
  },
  {
    title: 'Navigating International Taxation & DTAA',
    slug: 'navigating-international-taxation-dtaa',
    date: 'March 05, 2026',
    category: 'International Tax',
    summary: 'How multinationals can leverage Double Taxation Avoidance Agreements to optimize their global tax footprint.',
  },
  {
    title: 'The Strategic Value of Virtual CFO Services',
    slug: 'strategic-value-virtual-cfo-services',
    date: 'February 25, 2026',
    category: 'Advisory',
    summary: 'Why scaling SMEs need institutional-grade financial leadership long before they can afford a full-time CFO.',
  },
  {
    title: 'India-US DTAA Guide: Permanent Establishment, Business Profits, and Double Tax Relief',
    slug: 'india-us-dtaa-guide',
    date: 'February 3, 2026',
    category: 'US Cross-Border',
    summary: 'How Article 5 defines a permanent establishment, the 120-day construction and services PE thresholds, and how Article 7 attributes business profits under the India-US tax treaty.',
  },
  {
    title: 'US LLC Annual Compliance Calendar for Non-Resident Founders',
    slug: 'us-llc-annual-compliance-calendar-non-resident',
    date: 'January 9, 2026',
    category: 'US Cross-Border',
    summary: 'Annual reports, franchise tax, registered agent renewal, estimated tax dates, and why a domestic US LLC is now exempt from BOI reporting.',
  },
  {
    title: 'US Sales Tax Economic Nexus for Indian SaaS and Services Companies',
    slug: 'us-sales-tax-nexus-indian-saas-companies',
    date: 'November 22, 2025',
    category: 'US Cross-Border',
    summary: 'How economic nexus lets a US state require sales tax registration based on sales volume alone, no physical presence needed, and why SaaS taxability varies state by state.',
  },
  {
    title: 'Form 5471 vs 5472 vs 8858: Which One Applies to Your Foreign-Owned US Entity',
    slug: 'form-5471-5472-8858-foreign-owned-us-entity',
    date: 'October 15, 2025',
    category: 'US Cross-Border',
    summary: 'The direction test for these three IRS information returns, why a foreign-owned single-member US LLC almost always files Form 5472, and the penalties for missing it.',
  },
  {
    title: 'FBAR and FATCA for Indian Founders with a US LLC: What Must Be Disclosed',
    slug: 'fbar-fatca-us-llc-indian-founders',
    date: 'August 9, 2025',
    category: 'US Cross-Border',
    summary: 'The 10,000 dollar FBAR threshold, the separate FATCA Form 8938 thresholds, and how signature authority over a foreign account can trigger a filing on its own.',
  },
  {
    title: 'Delaware or Wyoming Incorporation for Indian Founders: EIN and ITIN Explained',
    slug: 'delaware-wyoming-incorporation-ein-itin-guide',
    date: 'June 27, 2025',
    category: 'US Cross-Border',
    summary: 'How to incorporate remotely, get an EIN without an SSN through Form SS-4, and the correct timing for an ITIN application.',
  },
  {
    title: 'US LLC vs C-Corp for Indian Founders: Which Structure Fits Your Startup',
    slug: 'us-llc-vs-c-corp-indian-founders',
    date: 'May 14, 2025',
    category: 'US Cross-Border',
    summary: 'LLC pass-through taxation and phantom income vs C-Corp taxation, why VC investors prefer a Delaware C-Corp, and the common two-entity structure for Indian founders.',
  },
  {
    title: 'Reassessment Notice Under Section 148: Time Limits & Response',
    slug: 'reassessment-notice-under-section-148-time-limits-and-response',
    date: 'August 19, 2026',
    category: 'Tax Audit',
    summary: 'How Section 148 reassessment notices work after the Finance Act 2021 reforms, the Section 148A show-cause step, current time limits, and how to respond.',
  },
  {
    title: 'Survey Under Section 133A: Rights & Obligations of Taxpayers',
    slug: 'survey-under-section-133a-rights-and-obligations-of-taxpayers',
    date: 'August 19, 2026',
    category: 'Tax Audit',
    summary: 'What an income tax survey under Section 133A can and cannot do, the business-hours rule, impounding limits, and what a taxpayer is and is not required to do.',
  },
  {
    title: 'Income Tax Appeal Process: CIT(Appeals) to ITAT',
    slug: 'income-tax-appeal-process-cit-appeals-to-itat',
    date: 'August 20, 2026',
    category: 'Tax Audit',
    summary: 'How the income tax appeal ladder works from CIT(Appeals) / Joint Commissioner (Appeals) to the ITAT, High Court and Supreme Court, the forms, fees, and filing timelines.',
  },
  {
    title: 'Faceless Appeal Scheme: How Income Tax Appeals Work Now',
    slug: 'faceless-appeal-scheme-how-income-tax-appeals-work-now',
    date: 'August 21, 2026',
    category: 'Tax Audit',
    summary: 'How the Faceless Appeal Scheme routes income tax appeals through the National Faceless Appeal Centre, which cases are excluded, and how to respond to a notice under this scheme.',
  },
  {
    title: 'Penalty for Under-Reporting & Misreporting of Income',
    slug: 'penalty-for-under-reporting-and-misreporting-of-income',
    date: 'August 21, 2026',
    category: 'Tax Audit',
    summary: 'How Section 270A penalties work: the difference between under-reporting and misreporting of income, the 50% and 200% penalty rates, and what counts as each.',
  },
  {
    title: 'Search & Seizure Under Income Tax: What Happens During a Raid',
    slug: 'search-and-seizure-under-income-tax-what-happens-during-a-raid',
    date: 'August 22, 2026',
    category: 'Tax Audit',
    summary: 'How an income tax search (Section 132) is authorised, what happens during the raid, your rights as a taxpayer, and how seized cash, documents and assets are handled.',
  },
  {
    title: 'Stay of Demand: How to Apply When You Dispute a Tax Assessment',
    slug: 'stay-of-demand-how-to-apply-when-you-dispute-a-tax-assessment',
    date: 'August 22, 2026',
    category: 'Tax Audit',
    summary: 'How to apply for stay of demand under Section 220(6) while your income tax appeal is pending, the 20% deposit benchmark, and what the Budget 2026 proposal to reduce it to 10% actually changes.',
  },
  {
    title: 'Vivad Se Vishwas Scheme: Settling Pending Tax Disputes',
    slug: 'vivad-se-vishwas-scheme-settling-pending-tax-disputes',
    date: 'August 23, 2026',
    category: 'Tax Audit',
    summary: 'How the Direct Tax Vivad Se Vishwas (VSV 2.0) scheme worked, why it closed to new declarations on April 30, 2025, and what options remain for settling a pending income tax dispute today.',
  },
  {
    title: 'Statement of Financial Transactions (SFT): High-Value Transaction Reporting',
    slug: 'statement-of-financial-transactions-sft-high-value-transaction-reporti',
    date: 'August 23, 2026',
    category: 'Tax Audit',
    summary: 'What Form 61A / the Statement of Financial Transaction reports, who must file it, the high-value transaction thresholds banks and registrars track, and why it shows up in your AIS.',
  },
  {
    title: 'Annual Information Statement (AIS) vs Form 26AS: What Is the Difference',
    slug: 'annual-information-statement-ais-vs-form-26as-what-is-the-difference',
    date: 'August 24, 2026',
    category: 'Tax Audit',
    summary: 'AIS, TIS, and Form 26AS explained: what each one shows, how they relate, and how to reconcile all three before filing your ITR.',
  },
  {
    title: 'Tax Audit for E-Commerce Sellers & Digital Businesses',
    slug: 'tax-audit-for-e-commerce-sellers-and-digital-businesses',
    date: 'August 25, 2026',
    category: 'Tax Audit',
    summary: 'How Section 44AB tax audit turnover thresholds apply to online sellers, how presumptive taxation under Section 44AD interacts with e-commerce, and how Section 194-O TDS and GST TCS fit together.',
  },
  {
    title: 'Prosecution Under Income Tax Act: When Non-Compliance Becomes Criminal',
    slug: 'prosecution-under-income-tax-act-when-non-compliance-becomes-criminal',
    date: 'August 25, 2026',
    category: 'Tax Audit',
    summary: 'When income tax non-compliance stops being a civil penalty matter and becomes criminal prosecution: willful evasion, failure to file, imprisonment ranges, and how compounding works.',
  },
  {
    title: 'Corporate Tax Rates in India: Domestic Company vs New Manufacturing Regime',
    slug: 'corporate-tax-rates-in-india-domestic-company-vs-new-manufacturing-reg',
    date: 'August 26, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Comparing Section 115BAA (22% concessional rate for domestic companies) with Section 115BAB (15% rate for new manufacturing companies), the conditions, exemption trade-offs, and effective tax rates for FY 2026-27.',
  },
  {
    title: 'MAT (Minimum Alternate Tax) vs AMT: Applicability & Computation',
    slug: 'mat-minimum-alternate-tax-vs-amt-applicability-and-computation',
    date: 'August 26, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How Minimum Alternate Tax under Section 115JB applies to companies at 15% of book profit, how Alternate Minimum Tax under Section 115JC applies to non-corporate taxpayers, and how MAT/AMT credit works.',
  },
  {
    title: 'Dividend Distribution & Taxation: Company and Shareholder Perspective',
    slug: 'dividend-distribution-and-taxation-company-and-shareholder-perspective',
    date: 'August 27, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How dividends are taxed in India after the abolition of Dividend Distribution Tax: shareholder-level taxability, TDS under Section 194, and what companies must do at the time of payout.',
  },
  {
    title: 'Buyback of Shares: Tax Implications for Companies & Shareholders',
    slug: 'buyback-of-shares-tax-implications-for-companies-and-shareholders',
    date: 'August 28, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How share buybacks are taxed in India after the October 2024 rule change: deemed dividend treatment for shareholders, Section 194 TDS, and the capital loss on cost of acquisition.',
  },
  {
    title: 'Statutory Audit Requirements for Private Limited Companies',
    slug: 'statutory-audit-requirements-for-private-limited-companies',
    date: 'August 28, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Why every private limited company needs a statutory audit under the Companies Act 2013 regardless of turnover, how auditor appointment and rotation work, and where CARO 2020 applies.',
  },
  {
    title: 'Board Meeting & AGM Compliance Calendar for Private Limited Companies',
    slug: 'board-meeting-and-agm-compliance-calendar-for-private-limited-companie',
    date: 'August 29, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Minimum board meeting frequency under Section 173, AGM deadlines under Section 96, and quorum rules every private limited company in India needs to track.',
  },
  {
    title: 'Related Party Transactions Under Companies Act: Disclosure & Approval',
    slug: 'related-party-transactions-under-companies-act-disclosure-and-approval',
    date: 'August 29, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Section 188 of the Companies Act 2013: which transactions need board approval, when shareholder approval kicks in, and how Form AOC-2 disclosure works.',
  },
  {
    title: 'Director Responsibility & Liability Under the Companies Act',
    slug: 'director-responsibility-and-liability-under-the-companies-act',
    date: 'August 30, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Director fiduciary duties under Section 166, when personal liability attaches, and the Section 164 grounds for director disqualification.',
  },
  {
    title: 'Winding Up / Strike Off a Private Limited Company: Process & Timeline',
    slug: 'winding-up-strike-off-a-private-limited-company-process-and-timeline',
    date: 'August 30, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How to close a private limited company through the Fast Track Exit (Form STK-2) route: eligibility conditions, documents required, filing steps, and realistic timelines.',
  },
  {
    title: 'Secretarial Audit: Applicability & What It Covers',
    slug: 'secretarial-audit-applicability-and-what-it-covers',
    date: 'August 31, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Who must get a secretarial audit under Section 204 of the Companies Act, the Rule 9 turnover and paid-up capital thresholds, and what a Form MR-3 report actually examines.',
  },
  {
    title: 'Charge Creation & Satisfaction (CHG Forms): ROC Compliance Guide',
    slug: 'charge-creation-and-satisfaction-chg-forms-roc-compliance-guide',
    date: 'September 1, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How to register and satisfy a charge on company assets with the Registrar: Form CHG-1, CHG-4, and CHG-9, filing timelines, condonation windows, and what happens if a charge is missed.',
  },
  {
    title: 'Related Party Loans & Section 185/186 Compliance',
    slug: 'related-party-loans-and-section-185-186-compliance',
    date: 'September 1, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'How Section 185 restricts loans to directors and Section 186 governs inter-corporate loans and investments under the Companies Act 2013, including limits, approvals, and penalties.',
  },
  {
    title: 'XBRL Filing Requirements for Companies',
    slug: 'xbrl-filing-requirements-for-companies',
    date: 'September 2, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Which companies must file financial statements in XBRL format with the MCA, the applicability thresholds, the AOC-4 XBRL deadline, and the penalty for missing it.',
  },
  {
    title: 'Corporate Social Responsibility (CSR) Compliance & Applicability',
    slug: 'corporate-social-responsibility-csr-compliance-and-applicability',
    date: 'September 2, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Section 135 CSR applicability thresholds for net worth, turnover, and net profit, the 2% spend rule, when a CSR committee is required, and the penalty for non-compliance.',
  },
  {
    title: 'Significant Beneficial Owner (SBO) Reporting Requirements',
    slug: 'significant-beneficial-owner-sbo-reporting-requirements',
    date: 'September 3, 2026',
    category: 'Corporate Tax & Compliance',
    summary: 'Who qualifies as a Significant Beneficial Owner under Section 90 of the Companies Act, the 10% threshold, and how to file Form BEN-1 and BEN-2 on time.',
  },
  {
    title: 'Udyam Registration for MSMEs: Process, Benefits & Eligibility',
    slug: 'udyam-registration-for-msmes-process-benefits-and-eligibility',
    date: 'September 4, 2026',
    category: 'MSME & Registrations',
    summary: 'Current MSME investment and turnover limits for micro, small and medium enterprises, how to complete Udyam registration, and the benefits it unlocks.',
  },
  {
    title: 'Shop and Establishment Registration: State-Wise Requirements',
    slug: 'shop-and-establishment-registration-state-wise-requirements',
    date: 'September 4, 2026',
    category: 'MSME & Registrations',
    summary: 'Who needs Shop and Establishment registration, how the Maharashtra Shops and Establishments Act works (Gumasta), and how requirements vary state to state.',
  },
  {
    title: 'Import Export Code (IEC): Registration Process & Benefits',
    slug: 'import-export-code-iec-registration-process-and-benefits',
    date: 'September 5, 2026',
    category: 'MSME & Registrations',
    summary: 'How to register for an Import Export Code (IEC) with the DGFT, who actually needs one, the annual update rule, and what happens if you miss it.',
  },
  {
    title: 'Professional Tax Registration & Compliance in Maharashtra',
    slug: 'professional-tax-registration-and-compliance-in-maharashtra',
    date: 'September 5, 2026',
    category: 'MSME & Registrations',
    summary: 'Maharashtra Professional Tax slabs, PTEC vs PTRC registration, due dates, and who is liable, for employers, professionals, and businesses in Nashik and Sillod.',
  },
  {
    title: 'Trademark Registration for Startups: Process & Timeline',
    slug: 'trademark-registration-for-startups-process-and-timeline',
    date: 'September 6, 2026',
    category: 'MSME & Registrations',
    summary: 'How startups register a trademark in India: choosing the right class, the Form TM-A filing process, realistic timelines, and the reduced fee available to DPIIT-recognised startups.',
  },
  {
    title: 'Startup India Registration vs DPIIT Recognition: What Is the Difference',
    slug: 'startup-india-registration-vs-dpiit-recognition-what-is-the-difference',
    date: 'September 6, 2026',
    category: 'MSME & Registrations',
    summary: 'Startup India registration and DPIIT recognition are often treated as two separate steps, but they are one and the same process. Here is what actually happens and where the confusion comes from.',
  },
  {
    title: 'MSME Udyam vs Startup India Recognition: Which Benefits Apply',
    slug: 'msme-udyam-vs-startup-india-recognition-which-benefits-apply',
    date: 'September 7, 2026',
    category: 'MSME & Registrations',
    summary: 'Udyam (MSME) registration and DPIIT Startup India recognition are two distinct schemes with different eligibility and different benefits. Here is which benefit comes from which, and whether a business needs both.',
  },
  {
    title: 'FSSAI Registration for Food Businesses: When Required',
    slug: 'fssai-registration-for-food-businesses-when-required',
    date: 'September 8, 2026',
    category: 'MSME & Registrations',
    summary: 'FSSAI Basic Registration, State License, and Central License explained: current turnover thresholds, which food businesses need which tier, and how to apply.',
  },
  {
    title: 'Trade License Requirements for Businesses in India',
    slug: 'trade-license-requirements-for-businesses-in-india',
    date: 'September 8, 2026',
    category: 'MSME & Registrations',
    summary: 'What a municipal trade license is, which businesses need one, how it differs from a Shop and Establishment license, and the general application process, with Nashik/Maharashtra context.',
  },
  {
    title: 'Section 12A & 80G Registration for NGOs & Charitable Trusts',
    slug: 'section-12a-and-80g-registration-for-ngos-and-charitable-trusts',
    date: 'September 9, 2026',
    category: 'Trusts & NGOs',
    summary: 'How Section 12A and Section 80G registration work for NGOs and charitable trusts: provisional vs regular registration, the Form 10AB renewal process, and validity periods.',
  },
  {
    title: 'Trust vs Society vs Section 8 Company: Choosing the Right NGO Structure',
    slug: 'trust-vs-society-vs-section-8-company-choosing-the-right-structure-for',
    date: 'September 9, 2026',
    category: 'Trusts & NGOs',
    summary: 'Comparing Trusts, Societies, and Section 8 Companies for an NGO in India: governing law, governance requirements, cost, and which structure suits which use case.',
  },
  {
    title: 'FCRA Registration: Foreign Contribution Compliance for NGOs',
    slug: 'fcra-registration-foreign-contribution-compliance-for-ngos',
    date: 'September 10, 2026',
    category: 'Trusts & NGOs',
    summary: 'FCRA registration eligibility, the prior permission route for younger NGOs, the FC-4 annual return, and why FCRA compliance has become higher-stakes for Indian nonprofits.',
  },
  {
    title: 'Taxation of Charitable Trusts: Exemptions & Compliance',
    slug: 'taxation-of-charitable-trusts-exemptions-and-compliance',
    date: 'September 11, 2026',
    category: 'Trusts & NGOs',
    summary: 'How Section 11 and Section 12 exemption works for charitable trusts: the 85% application requirement, accumulation rules, anonymous donation taxation under Section 115BBC, and 12A/12AB registration.',
  },
  {
    title: 'Annual Compliance Calendar for NGOs and Trusts in India',
    slug: 'annual-compliance-calendar-for-ngos-and-trusts-in-india',
    date: 'September 11, 2026',
    category: 'Trusts & NGOs',
    summary: 'A deadline-by-deadline compliance calendar for Indian NGOs and trusts: Form 10B/10BB audit report, ITR-7 filing, FCRA FC-4 return, and the 12A/80G renewal cycle.',
  },
  {
    title: 'CSR Fund Utilisation: Compliance for Receiving Trusts',
    slug: 'csr-fund-utilisation-compliance-for-receiving-trusts',
    date: 'September 12, 2026',
    category: 'Trusts & NGOs',
    summary: 'What a trust or NGO must do to legally receive and account for corporate CSR funding: CSR-1 registration, utilisation certificates, and reporting obligations to the funding company.',
  },
  {
    title: 'Political Party Donations & Section 80GGC Deduction',
    slug: 'political-party-donations-and-section-80ggc-deduction',
    date: 'September 12, 2026',
    category: 'Trusts & NGOs',
    summary: 'How the Section 80GGC deduction for donations to political parties works, the cash-donation restriction, and why the Income Tax Department is scrutinising these claims closely.',
  },
  {
    title: 'Payroll Compliance Checklist for Growing Startups in India',
    slug: 'payroll-compliance-checklist-for-growing-startups-in-india',
    date: 'September 13, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'A practical payroll compliance checklist for growing Indian startups: EPF and ESI triggers, TDS on salary, professional tax, and labour law registers at each headcount milestone.',
  },
  {
    title: 'Gratuity Payment Rules: Eligibility & Tax Exemption Limits',
    slug: 'gratuity-payment-rules-eligibility-and-tax-exemption-limits',
    date: 'September 14, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'The Payment of Gratuity Act 1972 five-year eligibility rule, the calculation formula, the Rs 20 lakh tax exemption ceiling, and employer funding options.',
  },
  {
    title: 'Labour Law Compliance for Startups: A Practical Overview',
    slug: 'labour-law-compliance-for-startups-a-practical-overview',
    date: 'September 14, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'Which labour laws typically apply to a small or growing Indian company, from Shops & Establishments to EPF, ESI, POSH, and the Maternity Benefit Act, explained for a first-time founder.',
  },
  {
    title: 'EPF Registration & Compliance for Startups and SMEs',
    slug: 'epf-registration-and-compliance-for-startups-and-smes',
    date: 'July 28, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'When EPF registration becomes mandatory at 20 employees, the 12% employer/employee contribution split across EPF, EPS and EDLI, and the ongoing compliance a startup or SME must handle.',
  },
  {
    title: 'ESI Registration: Applicability & Employer Compliance',
    slug: 'esi-registration-applicability-and-employer-compliance',
    date: 'August 4, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'When ESI registration applies at 10 or 20 employees, the Rs 21,000 wage ceiling, the 4% employer/employee contribution split, and the ongoing filing employers must handle.',
  },
  {
    title: 'Contract Labour vs Employment: Compliance Risks for Startups',
    slug: 'contract-labour-vs-employment-compliance-risks-for-startups',
    date: 'August 7, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'How the Contract Labour (Regulation & Abolition) Act 1970 registration and licensing thresholds work, and the misclassification risks startups face treating employees as contract labour.',
  },
  {
    title: 'Cost Plus Method (CPM) in Transfer Pricing: When It Applies',
    slug: 'cost-plus-method-cpm-in-transfer-pricing-when-it-applies',
    date: 'August 14, 2026',
    category: 'Transfer Pricing',
    summary: 'How the Cost Plus Method under Rule 10B(1)(c) works, which cost base it uses, when it is the most appropriate method for contract manufacturers and low-risk service providers, and why TNMM often replaces it in practice.',
  },
  {
    title: 'Profit Split Method (PSM) in Transfer Pricing: A Practical Guide',
    slug: 'profit-split-method-psm-in-transfer-pricing-a-practical-guide',
    date: 'August 17, 2026',
    category: 'Transfer Pricing',
    summary: 'How the Profit Split Method under Rule 10B(1)(d) allocates combined profit between associated enterprises, when it is the most appropriate method, and how contribution and residual profit split analyses differ.',
  },
  {
    title: 'Secondary Adjustment Under Transfer Pricing: Section 92CE Explained',
    slug: 'secondary-adjustment-under-transfer-pricing-section-92ce-explained',
    date: 'August 18, 2026',
    category: 'Transfer Pricing',
    summary: 'When Section 92CE secondary adjustment applies, the Rs 1 crore primary adjustment threshold, the 90-day repatriation window, the deemed-advance interest treatment, and the one-time additional tax alternative on unrepatriated excess money.',
  },
  {
    title: 'Minimum Wages Act Compliance for Employers',
    slug: 'minimum-wages-act-compliance-for-employers',
    date: 'September 15, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'How minimum wage compliance works in India after the Code on Wages 2019 replaced the Minimum Wages Act 1948, including the floor wage concept, state-wise rates, and employer penalties.',
  },
  {
    title: 'POSH Act Compliance: Internal Committee Requirements for Companies',
    slug: 'posh-act-compliance-internal-committee-requirements-for-companies',
    date: 'September 15, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'When a company must form an Internal Committee under the POSH Act 2013, who must sit on it, the annual report requirement, and penalties for non-compliance including licence cancellation.',
  },
  {
    title: 'Form 24Q vs Form 26Q: TDS Return Filing for Employers',
    slug: 'form-24q-vs-form-26q-tds-return-filing-for-employers',
    date: 'September 16, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'The difference between Form 24Q (salary TDS) and Form 26Q (non-salary TDS), quarterly due dates, and how both are renumbered as Form 138 and Form 140 under the Income Tax Act 2025 for FY 2026-27.',
  },
  {
    title: 'Perquisites & Fringe Benefits Taxation for Employees',
    slug: 'perquisites-and-fringe-benefits-taxation-for-employees',
    date: 'September 16, 2026',
    category: 'Payroll & Labour Compliance',
    summary: 'How rent-free accommodation, company cars, and other perquisites are valued and taxed for employees in India, including the revised Rule 3/Rule 15 valuation figures effective April 2026.',
  },
  {
    title: 'Form 10B/10BB Audit Report for Trusts: Applicability & Due Date',
    slug: 'form-10b-10bb-audit-report-for-trusts-applicability-and-due-date',
    date: 'September 17, 2026',
    category: 'Trusts & NGOs',
    summary: 'Which trusts and NGOs must file Form 10B vs Form 10BB, the Rs 5 crore income threshold and foreign-contribution trigger that decide between them, and the current filing due date.',
  },
  {
    title: 'One Person Company (OPC) Registration: Eligibility & Compliance',
    slug: 'one-person-company-opc-registration-eligibility-and-compliance',
    date: 'September 17, 2026',
    category: 'Company Incorporation',
    summary: 'Who can incorporate a One Person Company in India, the nominee requirement, why the old paid-up capital and turnover conversion thresholds no longer apply, and the ongoing compliance an OPC must maintain.',
  },
  {
    title: 'NRI Fixed Deposit Options: NRE vs NRO vs FCNR Comparison',
    slug: 'nri-fixed-deposit-options-nre-vs-nro-vs-fcnr-comparison',
    date: 'September 17, 2026',
    category: 'NRI Taxation',
    summary: 'NRE FD, NRO FD, and FCNR FD compared for NRIs: interest rates, taxability, TDS, repatriability, tenure, and currency risk for each fixed deposit type.',
  },
  {
    title: 'Double Taxation Relief for NRIs: Foreign Tax Credit Under Section 91',
    slug: 'double-taxation-relief-for-nris-foreign-tax-credit-under-section-91',
    date: 'July 18, 2026',
    category: 'NRI Taxation',
    summary: 'How Section 91 unilateral relief works for NRIs and residents with foreign income when India has no DTAA with the source country, how it differs from Section 90 DTAA relief, and how to claim it.',
  },
  {
    title: 'NRI Selling Agricultural Land Inherited in India: Tax & FEMA Rules',
    slug: 'nri-selling-agricultural-land-inherited-in-india-tax-and-fema-rules',
    date: 'July 24, 2026',
    category: 'NRI Taxation',
    summary: 'How an NRI sells inherited agricultural land in India: who can be the buyer, rural vs urban land capital gains treatment, TDS obligations, and repatriating the sale proceeds.',
  },
  {
    title: 'NRI Investing in Indian Real Estate: A Complete Compliance Guide',
    slug: 'nri-investing-in-indian-real-estate-a-complete-compliance-guide',
    date: 'July 30, 2026',
    category: 'NRI Taxation',
    summary: 'FEMA rules for NRIs buying residential and commercial property in India: what can and cannot be purchased, funding channels via NRE/NRO/FCNR, and repatriation of rental income.',
  },
  {
    title: 'Tax Implications for NRIs Working Remotely for Foreign Employers From India',
    slug: 'tax-implications-for-nris-working-remotely-for-foreign-employers-from',
    date: 'August 4, 2026',
    category: 'NRI Taxation',
    summary: 'What happens when an NRI works remotely from India for a foreign employer: residential status impact, taxability of foreign salary once resident, DTAA relief, and employer withholding.',
  },
  {
    title: 'NRI Life Insurance & ULIP Taxation Rules',
    slug: 'nri-life-insurance-and-ulip-taxation-rules',
    date: 'August 8, 2026',
    category: 'NRI Taxation',
    summary: 'Can NRIs buy Indian life insurance and ULIPs, which premium payment channels apply, when maturity proceeds are exempt under Section 10(10D), and TDS on payouts to NRIs.',
  },
  {
    title: 'Power of Attorney for NRIs: Property Transactions from Abroad',
    slug: 'power-of-attorney-for-nris-property-transactions-from-abroad',
    date: 'August 12, 2026',
    category: 'NRI Taxation',
    summary: 'How NRIs execute a Power of Attorney for Indian property from abroad: general vs special POA, apostille and consular attestation, the 3-month stamping deadline, and key risks.',
  },
  {
    title: 'NRI Demat Account: PIS vs Non-PIS Explained',
    slug: 'nri-demat-account-pis-vs-non-pis-explained',
    date: 'August 16, 2026',
    category: 'NRI Taxation',
    summary: 'What a PIS account is, when it is needed for NRI equity investment, how non-PIS (NRO-linked) accounts work, and the 2025 RBI change merging NRE and NRO PIS accounts.',
  },
  {
    title: 'Seafarer (Merchant Navy) Taxation: NRI Status & Exemptions',
    slug: 'seafarer-merchant-navy-taxation-nri-status-and-exemptions',
    date: 'August 17, 2026',
    category: 'NRI Taxation',
    summary: 'How residential status is determined for seafarers using the CDC day-counting rule, taxability of NRE salary for voyages outside Indian waters, and common compliance mistakes.',
  },
  {
    title: 'OCI vs NRI vs PIO: Tax & Compliance Differences Explained',
    slug: 'oci-vs-nri-vs-pio-tax-and-compliance-differences-explained',
    date: 'August 18, 2026',
    category: 'NRI Taxation',
    summary: 'OCI is an immigration status, NRI is a tax-residency status, and PIO no longer exists as a separate card. What each status means for property rights, FEMA investment eligibility, and Indian tax filing.',
  },
  {
    title: 'Employee Stock Option Pool (ESOP Pool) Sizing for Startups',
    slug: 'employee-stock-option-pool-esop-pool-sizing-for-startups',
    date: 'August 20, 2026',
    category: 'Startup Advisory',
    summary: 'How to size an ESOP option pool at seed, Series A, and Series B: pre-money vs post-money pool creation, founder dilution impact, pool refreshes, and board/shareholder approval mechanics.',
  },
  {
    title: 'Term Sheet Negotiation: Key Clauses Indian Founders Should Understand',
    slug: 'term-sheet-negotiation-key-clauses-indian-founders-should-understand',
    date: 'August 24, 2026',
    category: 'Startup Advisory',
    summary: 'Liquidation preference, anti-dilution, board control, vesting, and exit rights in an Indian VC term sheet: which clauses are market standard, which are founder-unfriendly, and what is actually binding.',
  },
  {
    title: 'SAFE Notes in India: Are They Legally Recognised?',
    slug: 'safe-notes-in-india-are-they-legally-recognised',
    date: 'August 27, 2026',
    category: 'Startup Advisory',
    summary: 'Why a US-style SAFE (Simple Agreement for Future Equity) is not a recognised instrument under Indian company law or FEMA, and how founders adapt it into a compliant convertible note or CCPS instead.',
  },
  {
    title: 'Startup Exit Strategies: Acquisition vs IPO vs Buyback',
    slug: 'startup-exit-strategies-acquisition-vs-ipo-vs-buyback',
    date: 'August 31, 2026',
    category: 'Startup Advisory',
    summary: 'A founder-level comparison of the three main startup exit routes in India: acquisition (share sale vs slump sale), IPO (including the SME exchange), and share buyback under the Companies Act.',
  },
  {
    title: 'Co-Founder Equity Disputes: Prevention & Resolution',
    slug: 'co-founder-equity-disputes-prevention-and-resolution',
    date: 'September 3, 2026',
    category: 'Startup Advisory',
    summary: 'Why co-founder equity disputes happen (unequal contribution, no vesting, unclear roles), how founder vesting and a shareholders\' agreement prevent them, and resolution paths once a dispute arises.',
  },
  {
    title: 'Cap Table Management: Common Mistakes Founders Make',
    slug: 'cap-table-management-common-mistakes-founders-make',
    date: 'September 7, 2026',
    category: 'Startup Advisory',
    summary: 'Why cap tables go wrong for Indian startups: stale updates after funding rounds, fully-diluted vs issued-basis confusion, dilution modeling mistakes, and reconciling against ROC filings.',
  },
  {
    title: 'Startup Winding Up: Fast Track Exit (FTE) Mode Guide',
    slug: 'startup-winding-up-fast-track-exit-fte-mode-guide',
    date: 'September 10, 2026',
    category: 'Startup Advisory',
    summary: 'What "Fast Track Exit" means for a startup shutting down today: why FTE is the old scheme name, how the current STK-2 process applies to a DPIIT-recognised startup, and a realistic timeline.',
  },
  {
    title: 'Startup Bank Account Opening: Documents & Common Rejections',
    slug: 'startup-bank-account-opening-documents-and-common-rejections',
    date: 'September 13, 2026',
    category: 'Startup Advisory',
    summary: 'The documents a newly incorporated Indian startup needs to open a current account, and the most common reasons banks reject or delay account opening, from address mismatches to shell-company flags.',
  },
]

const breadcrumbLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://agrawalkhandelwal.com' },
    { '@type': 'ListItem', position: 2, name: 'Blog', item: 'https://agrawalkhandelwal.com/blog' },
  ],
}

const itemListLd = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name: 'Tax Insights & Advisory; Blog Posts',
  description: 'Expert analysis on International Tax, GST, Transfer Pricing, UAE Corporate Tax, startup compliance, and NRI taxation from Agrawal Khandelwal & Associates LLP.',
  url: 'https://agrawalkhandelwal.com/blog',
  itemListElement: posts.map((post, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    url: `https://agrawalkhandelwal.com/blog/${post.slug}`,
    name: post.title,
  })),
}

// Regenerate at most hourly so the compliance calendar tracks the current month
export const revalidate = 3600

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
const MONTH_ABBR = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

type Deadline = { day: number; title: string; desc: string }

function getComplianceDeadlines(m: number, year: number) {
  const abbr = MONTH_ABBR[m]
  const prevM = (m + 11) % 12
  const prevLabel = `${MONTH_NAMES[prevM]} ${m === 0 ? year - 1 : year}`

  // Filings that recur every month (for the previous month's transactions)
  const recurring: Deadline[] = [
    { day: 7, title: 'TDS/TCS Deposit', desc: `Deposit of TDS/TCS deducted or collected for ${prevLabel}.` },
    { day: 11, title: 'GSTR-1 Filing', desc: `Monthly GSTR-1 for ${prevLabel} (taxpayers not under QRMP).` },
    { day: 15, title: 'PF & ESI Payment', desc: `Provident Fund and ESI contribution for ${prevLabel}.` },
    { day: 20, title: 'GSTR-3B Filing', desc: `Monthly GSTR-3B for ${prevLabel} (monthly filers).` },
  ]

  // Deadlines specific to certain months (month index 0 = January)
  const monthSpecific: Record<number, Deadline[]> = {
    0: [{ day: 31, title: 'TDS Return (Q3)', desc: 'Quarterly TDS return (Form 24Q/26Q) for Oct to Dec.' }],
    2: [{ day: 15, title: 'Advance Tax (4th)', desc: 'Final instalment (100%) of advance tax for the financial year.' }],
    4: [{ day: 31, title: 'TDS Return (Q4)', desc: 'Quarterly TDS return (Form 24Q/26Q) for Jan to Mar.' }],
    5: [{ day: 15, title: 'Advance Tax (1st)', desc: '1st instalment (15%) of advance tax. Form 16 to employees also due.' }],
    6: [
      { day: 15, title: 'TDS Return (Q1)', desc: 'Quarterly TDS return for Apr to Jun.' },
      { day: 31, title: 'ITR Filing', desc: 'Income tax return due for non-audit taxpayers.' },
    ],
    8: [
      { day: 15, title: 'Advance Tax (2nd)', desc: '2nd instalment (45%) of advance tax.' },
      { day: 30, title: 'Tax Audit Report', desc: 'Tax audit report (Form 3CD) filing due.' },
    ],
    9: [{ day: 31, title: 'TDS Return (Q2)', desc: 'Quarterly TDS return for Jul to Sep.' }],
    10: [{ day: 30, title: 'Audit ITR & 3CEB', desc: 'ITR for audit cases and transfer pricing Form 3CEB.' }],
    11: [
      { day: 15, title: 'Advance Tax (3rd)', desc: '3rd instalment (75%) of advance tax.' },
      { day: 31, title: 'GSTR-9 Annual', desc: 'Annual GST return (GSTR-9 / 9C) for the previous financial year.' },
    ],
  }

  const all = [...recurring, ...(monthSpecific[m] ?? [])].sort((a, b) => a.day - b.day)
  return {
    label: `${MONTH_NAMES[m]} ${year}`,
    items: all.map(d => ({ date: `${d.day} ${abbr}`, title: d.title, desc: d.desc })),
  }
}

export default function Blog() {
  // Shift to IST so the month rolls over at midnight India time, not UTC
  const ist = new Date(Date.now() + 5.5 * 3600 * 1000)
  const cal = getComplianceDeadlines(ist.getUTCMonth(), ist.getUTCFullYear())
  return (
    <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListLd) }} />
    <div style={{ background: 'var(--bg-surface)', minHeight: '100dvh', paddingTop: '100px' }}>
      <div className="section">
        <div className="container">
          <div style={{ textAlign: 'center', maxWidth: '800px', margin: '0 auto 4rem' }}>
            <span className="section-badge">Knowledge Center</span>
            <h1 className="section-title" style={{ fontSize: 'clamp(2rem, 5vw, 3rem)' }}>Tax Insights & Advisory</h1>
            <p style={{ color: 'var(--text-light)', fontSize: '1.05rem' }}>
              Expert analysis on the latest regulatory shifts, tax optimizations, and strategic financial guidance.
            </p>
          </div>

          {/* Compliance Calendar */}
          <div className="card" style={{ marginBottom: '3.5rem', borderLeft: '4px solid var(--accent)' }}>
            <h2 style={{ fontSize: '1.35rem', marginBottom: '1.5rem' }}>Upcoming Compliance Deadlines: {cal.label}</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 220px), 1fr))', gap: '1rem' }}>
              {cal.items.map((item, idx) => (
                <div key={idx} style={{ background: 'var(--bg-surface)', padding: '1.25rem', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border)' }}>
                  <div style={{ color: 'var(--accent)', fontWeight: 800, fontSize: '1.1rem', marginBottom: '4px' }}>{item.date}</div>
                  <div style={{ fontWeight: 700, color: 'var(--text-main)', marginBottom: '4px', fontSize: '0.95rem' }}>{item.title}</div>
                  <div style={{ fontSize: '0.83rem', color: 'var(--text-light)', lineHeight: 1.5 }}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Blog Posts */}
          <BlogGrid posts={posts} />

          {/* Closing CTA */}
          <div style={{ background: 'linear-gradient(135deg, var(--primary) 0%, var(--primary-light) 100%)', color: 'var(--white)', textAlign: 'center', marginTop: '5rem', borderRadius: 'var(--radius-lg)', padding: '4rem 2rem' }}>
            <h2 style={{ color: 'var(--white)', marginBottom: '0.75rem' }}>Have a Question on Any of This?</h2>
            <p style={{ color: 'rgba(255,255,255,0.8)', maxWidth: '520px', margin: '0.75rem auto 2.5rem' }}>
              Book a free consultation with our partners, or message us on WhatsApp for a quick answer.
            </p>
            <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
              <a href="https://calendar.app.google/Ln2Xg6PeDQ4dTrgT7" target="_blank" rel="noopener noreferrer" className="btn" style={{ background: 'var(--accent)', color: 'var(--white)', fontWeight: 700 }}>Book Free Consultation</a>
              <a href="https://wa.me/919527533506?text=Hi,%20I%20have%20a%20tax%20question." target="_blank" rel="noopener noreferrer" className="btn btn-secondary">Chat on WhatsApp</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    </>
  )
}
